### ISSUE TITLE
`ess-set-working-directory` should not change `default-directory`

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#1004]
I've been confused for years with the behaviour of Emacs regarding the active directories of the files I'm editing. I just realised it's `ess-set-working-directory` that changes it to the new working directory of R.

It seems that this behaviour is intended: https://github.com/emacs-ess/ESS/commit/40ebf0f71eb0677895506201fac6da4d6119ffa2. But I'm not sure why changing the REPL directory should affect the buffer I'm switching from.

Should we change this to preserve the active directory? The active directory influences UI commands like `M-x find-file`. I suspect I'm not the only one who is confused by this behaviour.

**Comment by jabranham** [comment]
I'm not sure I follow. Can you give an example of behavior you find confusing?

**Comment by lionel-** [comment]
After setting the working directory of the inferior to some new path, the active directory of the buffer I called `ess-set-working-directory` from becomes the new working directory of the REPL. Then if I call commands like `find-file` or `dired` from that buffer (e.g. to switch to a different file from the same directory), it's no longer browsing files in the right place (the original `default-directory`).

**Comment by jabranham** [comment]
I think the current behavior is correct. This way the working directory of the R process and the Emacs buffer are kept in sync. It's similar to how if you do, e.g. `M-x shell` then `cd /somewhere`, `default-directory` gets updated to `/somewhere`.

**Comment by lionel-** [comment]
Then I have two questions.

If the behaviour is correct, why don't we keep in sync the working directories of the R process and the Emacs buffer once a buffer gets attributed an R process? At least this way the behaviour would be predictable.

Second question, what is the practical purpose of this? Not only was it confusing me, it also gets in the way of my workflow.

**Comment by lionel-** [comment]
The first question is about the issue that the working directory of the R process and the Emacs buffer are not really kept in sync, they only are under certain circumstances, which makes the behaviour confusing and difficult to learn by induction.

The second question points to the possibility that it might not be a good idea to do this, even if another command like `cd` does it.

**Comment by jabranham** [comment]
Oh, I think I might see your point. I was talking about the inferior buffer but if you 1) navigate to an R file, 2) start a R process, then 3) call `ess-set-working-directory` from the R-mode buffer (i.e. the file, not the process) then the default-directory of the file points to the process's working directory, not the file's. Yes, I think that's undesirable. I think that files' default-directory should always be the directory that houses the file and that the process buffer's default-directory should always be its current working directory.

**Comment by jabranham** [comment]
Though I should mention I don't think I've ever used `ess-set-working-directory` before today :-) My workflow doesn't really call for changing working directories often.

**Comment by lionel-** [comment]
oh good, yes I agree the default-directory of the inferior buffer should be kept in sync with R's working directory. Maybe that was the original intent actually? Currently only the current buffer's directory is updated, so the inferior's is only changed if the command was called from there.

**Comment by jabranham** [comment]
Looking at the docstring and git history, it looks like the current behavior is intentional. I think it probably makes sense to change it, but let's wait for @vspinu to chime in. Maybe he can explain something we're missing.

If we do change it, this is a good function to move to `cl-defmethod` dispatching on `ess-dialect` and deprecate the `no-error` argument.

**Comment by vspinu** [comment]
The original idea was to synchronize inferior default-directory automatically, but that turned to be problematic because one would constantly ping and ask the R process for the working dir. 

The intent of `ess-set-working-directory` was to set both `default-directory` and R's working dir to same thing. For sure the behavior in the inferior is as intended. And, frankly, all this time I was using it (very often) from inferior only. So it didn't even occur to me that someone can use it from script buffers. The current behavior is pretty surely a bug. I think originally this command was only bound in the inferior map and then moved to ess-map as well. This is why the messup. 

Regarding the automatic setting of the script default directory to process dir, I think it would create havoc. I think it's best to figure out tools (like company completion) to understand that path directories are from the root and not from the local dir. 

Loosely related, I am increasingly bothered by R process not starting from the root of the project. I think @lionel- had an issue open somewhere for this and we didn't change this back then, but maybe it's time to revisit.

**Comment by lionel-** [comment]
Sounds good, I'll send a fix to update the process's default-directory and leave the calling buffer's unchanged. I'll also revisit the project stuff once I get the chance.

I finally submitted my thesis, so once I've defended I'm expecting to have more time on my hands to work on ESS in the next year!

**Comment by vspinu** [comment]
Congrats with the thesis! 

>  am increasingly bothered by R process not starting from the root of the project.

I quickly looked at it and we actually intend to start in the root, but it didn't work for me for at least 2 reasons. But in `inferior-ess` and that we don't recognize RStudio's `*.Rproj`. I think we should fix that.
