### ISSUE TITLE
ess-eval-function with tramp fails if local $TMP missing on remote

### ISSUE THREAD

**Issue by epruesse** [emacs-ess/ESS#1024]
Trying to `C-c` a function when using Tramp with a remote R session, I get this:

```
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/var/folders/rq/83r63b9569g91xz05q64vd8h0000gn/T/test.R!PFnUsY': No such file or directory
> 
```

It appears that ESS is using the local value of `$TMPDIR` to create the filename for a remote temp file. Since I'm going from Mac to Linux, the `/var/folders/...` user temp dir does not exist on the remote.

I've tried altering `ess-source-directory`, the only variable I could find containing the tmp dir name, but does doesn't seem to have any effect on the file ESS attempts to write to on the remote computer.
Running `ess-eval-function` with `$TMPDIR` not existing on the remote leads to this:

**Comment by epruesse** [comment]
I worked around this by adding

```lisp
(setq temporary-file-directory "/tmp")
```

to my `init.el`. It's probably still a bug to assume that `localhost:$TMP` will exist on another host.

**Comment by dapritchard** [comment]
The call stack that I observe for the call to `ess-eval-region-or-function-or-paragraph-and-step` is the following, where more recent calls are shown on top.
```
ess-make-source-refd-command
ess-tracebug-send-function
ess-eval-function
ess-eval-function-or-paragraph
ess-eval-region-or-function-or-paragraph
ess-eval-region-or-function-or-paragraph-and-step
```
The problem I believe occurs in the `ess-make-source-refd-command` function. The value that is bound to `proc-dir` is the value of `default-directory` for the inferior buffer, which has a local filepath. As a result `nil` is then bound to `remote`, and then later the value bound to `tmpfile` is constructed using `temporary-file-directory`, rather than `(tramp-get-remote-tmpdir remote)`.

**Comment by epruesse** [comment]
Thank you!
