### ISSUE TITLE
`M-x R` does not start the R process any more

### ISSUE THREAD

**Issue by gdario** [emacs-ess/ESS#1035]
Dear ESS team,

First of all, thank you so much for your fantastic work! Today I noticed that when I call `M-x R`, instead of the usual `R starting project directory?` message, a buffer appears to select the completion near point (`R-mode`, `Rd-font` etc.).
I see from the repo that a couple of days ago some modifications have been introduced in the `ess-mode.el` file, which affect the `run-ess-r` function. Now, I can't really read Emacs Lisp, but what I can see is that, while `M-x R` does not behave as it used to, `run-ess-r` correctly starts the R process. Could this be linked to the different behaviour?

The version (from MELPA) I am using is  20200815.803, on Emacs 27.1 on a Macbook Pro running Catalina (10.15.6).

Thanks again for your work!

**Comment by lionel-** [comment]
The change you're referring to (https://github.com/emacs-ess/ESS/commit/874c6f8d282d48b7991f29facd71b8928f68a124).

I don't understand how this could cause issues, and I don't understand the behaviour you're seeing. Now `R` is its own defun instead of an alias to `run-ess-r`, but unless you've used defadvice on the latter that shouldn't have any effect.

**Comment by lionel-** [comment]
oops! I forgot to make it interactive!

**Comment by lionel-** [comment]
Should be fixed, thanks for reporting!

**Comment by gdario** [comment]
Fantastic! Thanks a lot!
