### ISSUE TITLE
ess-command does not handle complex comannd well

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#1066]
For example,

 ```
(ess-command "library(dplyr); `est1BbK1dj` <- as_tibble(`est1`)" nil nil nil nil (get-process (buffer-local-value 'ess-local-process-name (current-buffer))))
```

will lead to an error:
```
    --> string:Error: unexpected ';' in ".ess.command(library(dplyr);"
```

**Comment by ShuguangSun** [comment]
Find the solution: surround it with `ess-r--without-format-command`.

But be careful that if we use some buffer-local variable to concat the cmd string to `ess-command`, it might need Emacs's `let` expression for a temperory variable.  For example https://github.com/ShuguangSun/ess-view-data/commit/51a9a514e1c50ac5ef4c1a8cd62a910446ab5fee#diff-54686ee7d495c26ac5351272a0760249ae60b392af5a563a43f60fa8cbd2c06eR378

**Comment by lionel-** [comment]
Hi @ShuguangSun. You do know that `--` separator means the function, variable, or macro is purely internal and will change without warnings right?

Also if you use that macro you'll alter the behaviour of ess-command, for intance it will not preserve `.Last.value`.

I think the proper solution is for you to wrap your command in curly braces `{` so that you supply a single expression. `ess-command` has not been documented to support multiple expressions.

**Comment by ShuguangSun** [comment]
Thanks. It is the solution.
