### ISSUE TITLE
Warning when setting initial major mode

### ISSUE THREAD

**Issue by nistara** [emacs-ess/ESS#1089]
I'm using Emacs 27.1 and ESS 18.10.3 and get the following error when I set the initial major mode to `ess-r-mode`:

`Warning (defvaralias): Overwriting value of ‘R-mode-hook’ by aliasing to ‘ess-r-mode-hook’`

The init.el line that leads to the above error is:
`(setq initial-major-mode 'ess-r-mode)`

I don't think it's affecting ESS as such, but the warning comes up when I start Emacs.
Thanks for this great package!

**Comment by nistara** [comment]
Note, I didn't get this warning when I used ESS 18.10.2, but I updated because of another issue with company mode (https://emacs.stackexchange.com/questions/58902/company-printing-stuff-to-console-in-ess)

**Comment by lionel-** [comment]
I'm not sure what is causing that warning. My guess is that something in your config writes to `R-mode-hook` _before_ loading ESS. If it wrote to it after, I think you would see a warning that `R-mode-hook` has been obsoleted in favour of `ess-r-mode-hook`.

I tried this to confirm this hypothesis:

```elisp
(defvar my-new-hook nil)
(add-hook 'my-old-hook nil)

(define-obsolete-variable-alias 'my-old-hook 'my-new-hook)
```

I don't see a warning but it turns out it was added right after Emacs 26.1, which I am running: https://github.com/emacs-mirror/emacs/commit/c912db0836.

Can you find out if your config or a package invoked by your config is trying to write to `R-mode-hook`? It should now be `ess-r-mode-hook`.

**Comment by nistara** [comment]
Thanks so much for your suggestions.

I tried to figure out what was trying to write to `R-mode-hook` but couldn't find anything other than the line `(setq initial-major-mode 'ess-r-mode)`). When I removed it, the warning went away on start-up, but it showed up each time I started an ess process. So that somehow seems to be triggering the warning. 

I was just able to solve this by installing the ESS from MELPA stable - so no warning now and everything works fine as far as I know at the moment (with 18.10.2)!!

**Comment by nistara** [comment]
Back with the same issue as described here though: https://emacs.stackexchange.com/questions/58902/company-printing-stuff-to-console-in-ess

It's not a deal breaker...just want to bring it to your attention. Thanks so much for this useful package!

**Comment by lionel-** [comment]
Since you're back on the old version, we can now inspect the variable because it won't be overwritten by defvaralias. Can you please:

- Close Emacs and restart it
- Immediately after startup do `M-x eval-expression` and evaluate: `R-mode-hook`

The output will be shown in the echo area as well as the Messages buffer, from which you can copy.

**Comment by nistara** [comment]
Sure, this is what I get when I evaluate the expression:
`(ess-smart-underscore-add-inf ess-r-package-enable-namespaced-evaluation ess-bp-recreate-all)`

I can share my init config as well if it'll be helpful...

**Comment by lionel-** [comment]
Thank you. It looks like the symbol is being hooked by this package: https://github.com/mattfidler/ess-smart-underscore.el/blob/aa871c5b0448515db439ea9bed6a8574e82ddb47/ess-smart-underscore.el#L388

We should probably just undeprecate that symbol to avoid this sort of issues.
