### ISSUE TITLE
Conflict between ess and eglot (or their dependencies?)

### ISSUE THREAD

**Issue by QuietApe** [emacs-ess/ESS#1130]
There seems to be a weird conflict between ess and eglot, when eglot is loaded (with a (require 'eglot) in .emacs), eldoc is not active in a ess-r-mode buffer, no help appears in the minibuffer and when trying to manually start eldoc-mode a 
>There is no ElDoc support in this buffer

is displayed. Same with a inferior-ess-r buffer. The only other error displayed is
>Warning [flymake analyses.R]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)

in flymake log.

Since eglot require flymake and eldoc from ELPA, I try to install or remove them consecutively, and it became weirder. With ELPA's flymake and eldoc and without eglot, eldoc works in ess-r- but not in the inferior-ess-r buffer. And with only ELPA's eldoc, everything is fine.
But with the development version of emacs, everything works without problem (possibly because the builtin versions of flymake and eldoc meets the requirement of eglot).

I guess something goes wrong for ess when an ELPA package replace a builtin one, but i don't really see error message anywhere.

If there is a way to generate a log that I didn't know about, I would be happy to help!

**Comment by jabranham** [comment]
I think this is a bug in eldoc/Emacs, not ESS. Emacs 27.1 ships with code that defines `eldoc-documentation-function` as `#'ignore` so when eglot reloads eldoc to get a newer version, `eldoc--documentation-strategy-defcustom` calls `defcustom`, which does not assign the value because `eldoc-documentation-function` is already bound. So you wind up with `eldoc-documentation-function` being set to `ignore` in an ESS buffer if eglot hasn't been activated, only `require`'ed. 

I've submitted this as a bug report to eldoc/Emacs so hopefully it will get fixed soon. Here's the bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47388

**Comment by joaotavora** [comment]
> Emacs 27.1 ships with code that defines eldoc-documentation-function as #'ignore

yes 

> You wind up with eldoc-documentation-function being set to ignore

yes

:thinking:

**Comment by jabranham** [comment]
Eldoc upstream didn't see an issue with this so I implemented a workaround in 9ff5fc64587ffa86bcbd3be94120bd9bcd58a49c @QuietApe let me know if you experience any other issues

**Comment by QuietApe** [comment]
Thanks !
Will do if I see anything, but it works as expected so far.
