### ISSUE TITLE
ess-execute-screen-options invisibly

### ISSUE THREAD

**Issue by izahn** [emacs-ess/ESS#165]
I would like for the output width to match with width of the window, and found that I can accomplish this by adding `ess-execute-screen-options` to`window-size-change-functions`. But this breaks some org mode functionality by inserting e.g., `options(width=100, length=99999)` in the buffer. It looks like this can be made silent by changing 

```
(ess-eval-linewise (format "options(width=%d, length=99999)"
                                 (- (window-width) 2))
                         nil nil nil 'wait-prompt)
```
to 
```
(ess-eval-linewise (format "options(width=%d, length=99999)"
                                 (- (window-width) 2))
                         t nil nil 'wait-prompt)
```
so I've re-defined this function locally with this modification. Any chance this can be changed in ESS (or an option provided to make `ess-execute-screen-options` work invisibly)?

PS: in case someone is interested, this is the code I currently use to update the width automatically:
```

  (defun my-ess-fix-width ()
    (if (string= ess-language "S")
        (ess-eval-linewise (format "options(width=%d, length=99999)"
                                   (- (window-width) 2))
                           t nil nil 'wait-prompt)))

  (defun my-ess-execute-screen-options (foo)
    "cycle through windows whose major mode is inferior-ess-mode and fix width"
    (interactive)
    (setq my-windows-list (window-list))
      (while my-windows-list
        (when (with-selected-window (car my-windows-list) (string= "inferior-ess-mode" major-mode))
          (with-selected-window (car my-windows-list) (my-ess-fix-width)))
        (setq my-windows-list (cdr my-windows-list))))

  (add-to-list 'window-size-change-functions 'my-ess-execute-screen-options)
```
It seems to work well.

**Comment by vspinu** [comment]
> PS: in case someone is interested, this is the code I currently use to update the width automatically:

I think I would like this as well. We can have a var like `ess-auto-update-screen-options`. If non-nil ESS will update it dynamically.  We can also have some handy UI to set it alongside the width parameter.

**Comment by vspinu** [comment]
> Any chance this can be changed in ESS (or an option provided to make ess-execute-screen-options work invisibly)

In principle we can if we show an explicit message. Otherwise we can always add a new parameter to `ess-execute-screen-options`.

**Comment by mmaechler** [comment]
I agree we should provide automatic updating of  `getOption("width")`, i.e., reset `options(width = *)`, 
i.e., something like @vspinu 's proposed  `ess-auto-update-screen-options`.

About visibility:  I think we should not be like Microsoft Windows (used to be), and do too many things hidden from the user  ((as an R-core member, I frequently want to `debug(<low-level function>)` and that is often quite broken, because ESS calls that same function, under the hood, *during* the debugging session)).   Consequently, I'd prefer visibility of the `options()` changes.  This also has a didactical effect: The ESS R users will implicitly be taught about the effect of using  `options(width = <n>)`.    Consequence: We'd want the *visibility* of `(ess-execute-screen-options .)` also be configurable.

**Comment by izahn** [comment]
I agree that having the options change visible is a fine default. In my particular use case that was breaking other functionality, though that may well be considered an org mode bug rather than an ESS issue. Bottom line, I'll be happy if there is an option to control visibility, I don't really care what the default is.
