### ISSUE TITLE
Test cases for indentation

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#174]
Since the indentation code is rather meaty, it is difficult to change it without breaking things. It would be great to have systematic tests for indentation to reduce the probability of regressions. I will write a PR for this later this week.

I put together this collection of test cases, but I probably forgot many things. Feel free to complete the list:
```r
### Function declarations

fun <- function(arg,
                arg) {
    body
}

function(
    arg,
    arg
    )
    {
        body
    }

function(arg_fun(sub_arg,
                 sub_arg),
         arg) {}

function(arg, x = fun(
                  arg),
         arg) {}



### Function calls

fun_call(arg,
         arg)

fun_call(
    arg,
    arg
    )

fun_call(arg = (
    stuff         # bug?
    ),            #
         arg)

fun_call(arg = fun(
             stuff
    ),
         arg)



### Blocks

function()
    {
        body
    }

fun_call(arg = {
             stuff
         },
         {
             stuff
         }, arg = {
             stuff
         }, {
             stuff
         }
         arg)

fun <- call({
    stuff
}, {
    stuff
},
            {          # bug
                stuff  #
            }          #
            )          #

fun_call(function(x) {
             body
         },
         function(x) {
             body
         })

{
    {
        stuff
    }
}

{{
     stuff
 }
}


### Control flow

if (cond) {
    stuff
} else {
    stuff
}

if (cond) {
    stuff
}
else {
    stuff
}

if (cond)
    {
        stuff
    } else
        {
            stuff
        }

if (cond)
    {
        stuff
    }
else
    {
        stuff
    }

for (seq)
    {
        stuff
    }

for (seq) {
    stuff
}



### Continuation lines

stuff %>%
    stuff %>%
        stuff

{
    stuff %>%
        stuff %>%
            stuff
} %>%
    stuff %>%
        stuff

(
    stuff %>%
        stuff %>%
            stuff
    ) %>%
    stuff %>%
        stuff


[
 stuff %>%
     stuff %>%
         stuff
 ] %>%
     stuff %>%
         stuff

stuff %>%
    stuff %>%
        if (cond) {
            stuff %>%
                stuff %>%
                    stuff
        } else {
            stuff %>%
                stuff %>%
                    for (vec) {
                        stuff
                    } %>%
                        stuff %>%
                            stuff
        } %>%
            stuff %>%
                stuff


ggplot() +
    geom(lhs -
             rhs
         ) +
        geom()

{
    ggplot() +
        geom() +
            geom()
}

stuff +
    fun(x = arg,
        fun((lhs - rhs
             arg
             ) /
                arg)
        )
```

These examples are indented using RRR style, but we also need tests tailored to other styles/settings.

**Comment by vspinu** [comment]
Great work! Thanks.

It would be nice if each snippet were numbered `## 1`, `## 2` within each section so that we could refer to the specific pattern in communication.

For the same reasons would be nice to use `arg1, arg2, ...`, `stuff1, stuff2, ...` within each snippet. 

Also instead of `x = ` please use `arg = ` because `x = ` makes exactly 4 characters and it's not immediately  obvious what rule is used in those cases. On the right side of ` = ` would be nice to use `val`. Like `arg1 = val1`.

Would you PR on this?  How about `test/styles/RRR.R`?

Once we are done with the basic test suit for RRR style would be good to sleep on it for a while and then replicate this file with different settings. Hopefully not too many.

**Comment by vspinu** [comment]
I think `)` in 

```
fun_call(arg = fun(
             stuff
    ),
         arg)
```
is also a bug. But it's a very rare pattern, so we can leave with this for now.

**Comment by lionel-** [comment]
I was thinking of having the same test cases for different settings:
`styles/RRR.R`, `styles/C++.R`, `styles/misc1.R`, `styles/misc2.R` (2 additional configurations should be enough to start with).

They would have the same tests but different comments documenting known bugs.

**Comment by vspinu** [comment]
Yes. I have the same in mind. But we should sleep a bit on it and may be change and document `RRR.R` first. Then replicate it. Otherwise every change should be done multiple times.  I don't think we should have more than 3 files. Just pick most common 3 modifications of RRR and leave with it.

**Comment by vspinu** [comment]
Actually I have a better idea. We can have one file RRR.R and generate all others automatically with different settings. Each time RRR.R is modified we should re-run the shell script to re-generate all others.

**Comment by mmaechler** [comment]
I like the idea!    Nobody mentioned the already existing test examples (for 'RRR'), in
`etc/R-ESS-bugs.R`, i.e.
  https://github.com/emacs-ess/ESS/blob/master/etc/R-ESS-bugs.R

**Comment by vspinu** [comment]
> So, please start your new file by moving the indentation examples from R-ESS-bugs.R to the new file.

@lionel-  is aware of that file and he used it as a reference.That file is for bug tracking and is frequently modified which makes it unsuitable for automated testing (see the my comment on automated replication). 

We also want the file to be structured by indentation type so that it can serve as examples of indentation styles for other people.  `R-ESS-bugs.R` is organized  on `fifo` principles and I don't think we can do better.

What @lionel-  did is already pretty comprehensive and systematic.  There might be a few indentation test relating to comments what are in `R-ESS-bugs.R` but are missing here.  But that I can fix myself once the test suit is merged.

**Comment by lionel-** [comment]
closed by #175

**Comment by mmaechler** [comment]
As it is about indentation - and the new changes... let me add this here: I find the above indentation wrong (in RRR)  ... (and yes, please instruct us how indentation issues should be added given the new test directory, run-tests, and all that).

**Comment by vspinu** [comment]
> how indentation issues should be added given the new test directory, run-tests, and all that

Ideally there should be no need for new indentation tests. In case any are still added (like the above) it should comply with the naming conventions in RRR.R file (that should be self explanatory). All other style files are generated with `generate-indent-cases` script in `./test` subdir or with  `make generate-indent-cases`. Tests are run with `./test/run-tests` or `make test`.

**Comment by mmaechler** [comment]
I've added another case to `RRR.R` which differs from previous behavior ... 
Thank you @vspinu for the instruction / confirmation about how to proceed. I've tended to add more comments than there were in the other examples in `RRR.R`   I assume that's still within naming conventions.

**Comment by vspinu** [comment]
I am not sure what the best workflow should be but maybe we should continue using `ESS-R-bugs.R` for broken cases with all the comments that we need. Once those are fixed we make new test cases in the test files whenever necessary. The purpose of test files is that they will be used on travis eventually, and that people can use them as a reference for our styles. So, I think, it would be nice if those files didn't contain broken tests.

Also, comments like `###     ^-- should be here` are not very useful in test files because auto-generated cases with different styles than RRR will not match those anyways.

**Comment by lionel-** [comment]
Vitalie, I'm looking into this bug but test generation is broken for me right now. 

After [this commit](https://github.com/emacs-ess/ESS/commit/2b023e39f0c91a18fd43acd28a7a82e918aec0cc), I get: `Cannot open load file: ert`

**Comment by lionel-** [comment]
About test naming conventions, it'd be good to keep with the standardised and numbered names that are currently used in the test files because real project names such as `x.gt.10` are distracting.

Also, it's best to make each test a minimal working example. So instead of 
```r
## 4
isFoo <- function(x,y) {
   (if(cond(x)) foo(x,y, extra.stuff) else TRUE) &&
                                                   bar(x,y, and.some.more.arguments)
```
this is clearer:
```r
## 4
{
    (stuff) &&
              TRUE
}
```

Finally, I don't think we should document the bug in `R-ESS-bugs.el`, since we have github issues to discuss this.

**Comment by vspinu** [comment]
> Vitalie, I'm looking into this bug but test generation is broken for me right now. 

It's probably emacs version thingy. It works for me with emacs24.3. The previous script line didn't work, just as you mentined in the comments in run-script.

> Finally, I don't think we should document the bug in R-ESS-bugs.el, since we have github issues to discuss this.

Indeed. Old habits die hard.

**Comment by mmaechler** [comment]
Thank you @vspinu
> I am not sure what the best workflow should be but maybe we should continue using ESS-R-bugs.R for broken cases with all the comments that we need. Once those are fixed we make new test cases in the test files whenever necessary..

@lionel-, I don't agree at all with github issues being enough.
The standalone sources (e.g., the tarball) should contain such things.
In Free Software (see http://fsf.org/ if you think "free" means "for free",
   it means *much* more!), the source counts quite a bit, and what we are
currently offered on a commercial website is nice and helpful, but I want
keep the assets in the source.
