### ISSUE TITLE
Developer mode gives wrong enclosing environment to new functions

### ISSUE THREAD

**Issue by lawremi** [emacs-ess/ESS#186]
When loading a new function (i.e., one that does not already exist within the namespace) inside a developer-mode-enabled package via C-c C-f, the new function gets .GlobalEnv as its enclosure, where that really should be the namespace of the package.

**Comment by vspinu** [comment]
This was actualy by design to simplify the management and to avoid asking user for where to load the function.

What is the concrete use case when the current system will not work for you? You load a function in .GlobalEnv and all functions from your package should see it as such. So it's equivalent to loading it in your namespace except of some corner cases when the function overwrites imported stuff.

**Comment by lionel-** [comment]
I also think this would be nice. `devtools::load_all()` will load in the correct namespace, so we can get multiple definition floating around, with the one in global env prevailing. I got bitten by this a few times.

To avoid asking users where to load it, we could check if the function is defined in a file in a directory called `R`. If it is, we'd look for a `DESCRIPTION` file to get the name of the package (sometimes the directory containing the package and the real package name are different). And we'd only ask the user if these steps fail.

**Comment by lionel-** [comment]
> And we'd only ask the user if these steps fail.

Or better, simply use the global env as is the case now.

**Comment by mmaechler** [comment]
I tend to agree with @lionel- and @lawremi .  I really have had the same thought as @lionel- above: ESS should look to see if the file in questions resides inside a directory named 'R' (and possibly if there's a DESCRIPTION above), and in that case it should try really hard to find the correct namespace.  
Now, I'm dreaming on {recapturing a dream I've had several times for many months...}: If the function (or other object! - think of setMethod(.)) does not exist yet in the namespace, ESS should again be smart and look at the NAMESPACE file.  If that already has an export(.), it should do it in the namespace *and* add it to the package environment; otherwise the new object is only in the namespace (but of course, if it is a function, the function's `environment(.)` must be the namespace, and not globalEnv !).

**Comment by lawremi** [comment]
Just to clarify, I was suggesting that we just get the enclosing environment right, even if the function is assigned into the global environment. If the enclosing environment is incorrect, then the function will not be able to use non-exported symbols from the namespace.

**Comment by vspinu** [comment]
> To avoid asking users where to load it, we could check if the function is defined in a file in a directory called R. 

This is one is already there. When you open a file in a package and that package is in the `ess-developer-packages` list the developer mode is automatically turned on.

> If that already has an export(.) for our object, it should put it in the namespace and add it to the package environment; otherwise the new object is only put into the namespace (but of course, if it is a function, the function's environment(.) must be the namespace, and not globalEnv !).

I think this will bit fragile and will lead to different final results for different functions which will surely be confusing for the end user. I would simply add the object to both, namespace and package environments.  

>  then the function will not be able to use non-exported symbols from the namespace.

Ah. Of course. I am bitten by this myself on a regular basis. I will have a look at it.
