### ISSUE TITLE
Making ESS more compatible with `package.el`

### ISSUE THREAD

**Issue by milkypostman** [emacs-ess/ESS#2]
It would be nice to have ESS be more friendly to being installed with `package.el` which means using autoload in the proper places.  Is there any insight into what would need to be done to make this happen?

**Comment by raxod502** [comment]
I am really confused at why ESS still includes an `ess-autoloads.el` file instead of just declaring `;;;###autoload` comments like every other package. Is there a reason for this? It caused me [some confusion](https://github.com/raxod502/straight.el/issues/61) when trying to get ESS to work with my package manager.

**Comment by lionel-** [comment]
We are slowly modernising the codebase.

**Comment by jabranham** [comment]
I think we can close this issue now?

**Comment by vspinu** [comment]
Yes. Thanks @jabranham  for all the work!
