### ISSUE TITLE
Ess interacts badly with swiper package

### ISSUE THREAD

**Issue by stevenbagley** [emacs-ess/ESS#305]
Because ess-noweb-mode calls make-variable-buffer-local on post-command-hook, it breaks the command candidate list in swiper, a general-purpose search/completion package in emacs.

Exact description of problem is here: abo-abo/swiper#433

I think this is similar to #215.

Thanks.

**Comment by vspinu** [comment]
Fixed. Thanks. 

Just for the record,, `ess-noweb` is obsolete and is heading towards deletion from ESS in the near future.

**Comment by vspinu** [comment]
Unfortunately I need to revert the fix. Not making post-command buffer local renders ess-noweb non-functional. We plan to remove ess-noweb from core within a month. So this issues should be fixed soon anyways.

**Comment by nemashimMe** [comment]
I have an issue with the swiper slider:
I just cant figure out why the slider params start off screen.
transform: translate3d(1000px, 0px, 0px);
Why doesn't it start at :0 instead of 1000px?

Link :http://meiranamit.com/wordpress-4.3.1-he_IL/wordpress/#top

Any advice on this matter is appreciated:-)

**Comment by jabranham** [comment]
ess-noweb stuff is now obsolete, poly-R is the replacement
