### ISSUE TITLE
jump to function definition?

### ISSUE THREAD

**Issue by yitang** [emacs-ess/ESS#307]
Hello, I wonder if there is a way to jump to and edit the function definition? very similar to `ess-dump-object-into-edit-buffer` but the editing needs to be applied to the original source file.

Thank you very much.

Y

**Comment by vspinu** [comment]
Unfortunately not. You have to use external tools like etags or `imenu-anywhere`. You can generate R/C/Cpp tags for any directory with `C-c C-e C-t`.

**Comment by lionel-** [comment]
Just a note that universal-ctags (the successor of exhuberant-ctags) has added rough support for R files. This is compatible with the etags plugin of the new (and great!) xref infrastructure in Emacs 25.

@vspinu I wonder if we should have a user variable containing a list of development libpaths. Then we'd have one command for regenerating all TAGS file in all packages inside those libpaths. Finally, we'd have a xref plugin to handle lookup of `foo::bar` objects. It would look for a `foo` package inside the libpaths, and if it finds one, defer the lookup to the etags plugin with the relevant TAGS file. Also if a R process is active and point is on an unqualified `foo`, we could check if the parent environment of `foo` is a namespace to get the package name.

We could also have another ESS xref meant as a last resort that would dump the object in an edit buffer. That's how RStudio works as well.

This would be a nice complement to `imenu-anywhere`, especially once everything is nicely integrated under a common xref interface.

**Comment by lionel-** [comment]
If anyone wants to work on this, that would be a great project to get involved in ESS! :)

**Comment by vspinu** [comment]
> Just a note that universal-ctags (the successor of exhuberant-ctags) has added rough support for R files. 

Good to know.

>  Then we'd have one command for regenerating all TAGS file in all packages inside those libpaths. Finally, we'd have a xref plugin to handle lookup of foo::bar objects

This sound more like a job for a generic tag plugging. There is [ggtags](https://github.com/leoliu/ggtags) which I still have to try out. I am still using plain etags interface myself.

> Also if a R process is active and point is on an unqualified foo, we could check if the parent environment of foo is a namespace to get the package name.

This could be a good idea. We can ask R for the location of its libraries and then index those libraries on demand with `utils::rtags`. Libraries loaded with devtools should already have source locations so we should use those.

**Comment by lionel-** [comment]
> This sound more like a job for a generic tag plugging.

Maybe. The challenge is to target relevant packages so that we don't overwhelm the user with many sources. A `bar()` function could be defined in several packages and we only want to propose location for the one relevant package. I think only ESS can provide that sort of refinement.

> We can ask R for the location of its libraries and then index those libraries on demand with utils::rtags

Those libraries will be libraries of built packages, that we can't use for this purpose. So we need the folders where the user stores his R packages, which I call "development libpath". That's why I was thinking to handle this with a manually managed user variable. Though we could also manage automatically when `ess-r-package-mode` is activated.

**Comment by yitang** [comment]
> @vspinu I wonder if we should have a user variable containing a list of development libpaths. Then we'd have one command for regenerating all TAGS file in all packages inside those libpaths. Finally, we'd have a xref plugin to handle lookup of foo::bar objects. It would look for a foo package inside the libpaths, and if it finds one, defer the lookup to the etags plugin with the relevant TAGS file. Also if a R process is active and point is on an unqualified foo, we could check if the parent environment of foo is a namespace to get the package name.

sounds really good! 

it would be really nice to have the `jump to testing function` function.

**Comment by vspinu** [comment]
> Those libraries will be libraries of built packages, 
Actually I would like to be able to jump to those sources. 

> So we need the folders where the user stores his R packages, which I call "development libpath"

Cannot we re-use `ess-r-package-library-path` for this?

**Comment by lionel-** [comment]
> it would be really nice to have the jump to testing function function.

I use the following for this:

```lisp
(defun my-ess-open-testfiles ()
  (interactive)
  (let* ((pkg-path (cdr (ess-r-package-get-info)))
         (test-path (-reduce-r #'expand-file-name
                               (list "testthat" "tests" pkg-path))))
    (helm-find-files-1 (file-name-as-directory test-path))))
```

> Cannot we re-use ess-r-package-library-path for this?

Oh yes, I forgot about that one. This is a leftover of the old UI no? Should we make it a plural `paths` before the release?

**Comment by lionel-** [comment]
> Should we make it a plural paths before the release?

otoh most people probably have only one dev libpath. We can extend this variable to accept a list of paths in the future even if it's singular, so let's not worry about it.

**Comment by vspinu** [comment]
>> On Wed, Apr 27 2016 03:46, Lionel Henry wrote:

> Oh yes, I forgot about that one. This is a leftover of the old UI no? Should
> we make it a plural `paths` before the release?

Sure.

**Comment by lionel-** [comment]
sorry for spamming, I forgot to reply to this:

> Actually I would like to be able to jump to those sources.

But built packages are bytecode compiled, they don't have sources. The best we can do is dump the source the R process gives us in an edit buffer.

**Comment by yitang** [comment]
> But built packages are bytecode compiled, they don't have sources. The best we can do is dump the source the R process gives us in an edit buffer.

I look forwarding to having this feature!

**Comment by lionel-** [comment]
> I look forwarding to having this feature!

No one is planning to work on this at the moment so anyone who wants to have a go at this project would be heartily welcomed :)

**Comment by yitang** [comment]
> No one is planning to work on this at the moment so anyone who wants to have a go at this project would be heartily welcomed :)

I am very interested in doing it. I'd be proud if I could implement those features that I feel useful. I've done some elisp developments, but not as complex as ESS. So I wonder if you could mentor me for this project? I need some guidance, particually on where to start with.

**Comment by lionel-** [comment]
Great!

You can start by writing a function that looks for all folders inside `ess-r-package-library-path` to detect packages (we can't just assume every folder will be packages). There is some code for detection in ess-r-package.el. Once you have that list of pkg folders, you can write the function that rebuilds the TAGS in each one of them. You can start by using the ESS function that builds TAGS, we can generalise that one later.

For the xref plugin, the tricky part is probably to correctly defer lookup to the etags xref plugin with the right TAGS location (see lisp/progmodes/etags.el in Emacs sources). You'll first have to check that it's even possible at all, I've been assuming it is because xref-etags has a method about TAGS file location.

xref works with `eieio` OO code, you'll first have to get familiar with this framework. Maybe a good way to start is to write an xref plugin for imenu-anywhere that would be quite useful as well. Or simply an xref plugin that dumps the source from the R process.

**Comment by lionel-** [comment]
> Or simply an xref plugin that dumps the source from the R process.

Note that we already have functions for that, e.g. `C-c C-e C-d`. So all there it to do is write the xref plugin, which is why it may be a simple way to get familiar with it.

**Comment by vspinu** [comment]
One question is whether to automatically include TAGS that we search into global `tags-table-list` or not. On one hand you would like to make the R tags automatically available to other backends like helm-etags, on the other hand you don't want to clutter global tag tables.  I think a compromise would be to make `tags-table-list` buffer local in R projects but that would interfere with user patterns that use `visit-tags-table` directly. Should be investigated.

**Comment by lionel-** [comment]
Maybe we can keep our own table in a different variable and user can still manage the global one as they want (i.e., add R packages there)?

The way I see it, adding the ESS xref plugin just makes sure that when an R object is looked up, we get only a relevant R package source (and not something from a python project etc). Other xref plugins will take care of the rest if we don't find anything.

The source dumping can then occur at two moments: in the main ESS plugin if an option is enabled. In that case we don't give the chance to other plugins. Or in another xref plugin that should ideally be the last in the list of backends (probably the only way is to rely on the user to make sure that's the case).

I'm new to this TAGS stuff so I may be misunderstanding some aspects of the problem.

**Comment by vspinu** [comment]
> In that case we don't give the chance to other plugins. 

I am not a big fan of this chained plugin system in xref. I strongly believe that this contextual ref lookup is actually a bad idea. So I personally use 4 different keys for different lookups. One for tags, one for imenu-anywhere, one for mode specific xref and the last one for emacs-lisep-xref. This way I have a refined and predictable control over where I jump. 

Having one key for all and resolve based on context is just silly. You will end up with annoying and unexpected jumps (like etags from elisp doc/info instead) and there is no way to jump to elisp doc from modes which define their xref plugin.

So I am not really in a hurry to make xref plugin for imenu-anywhere, nor I think we should be too much concerned with passing the chain of execution to other plugins in xref. Let's just do our best to find our definitions.

**Comment by lionel-** [comment]
hmm... I don't have a definite opinion on this yet. In any case we can probably accommodate both approaches by let-binding the backend variable in commands for jumping with a specific backend. This way we reuse the xref interface in case of multiple matches (though that should be rare with our design).

Personally I think it makes sense to have this chain in R buffers: general ESS plugin → imenu-anywhere → source dump. I don't think this can get confusing.

Maybe the xref backends variable is best kept as mode-local?

**Comment by lionel-** [comment]
> Personally I think it makes sense to have this chain in R buffers: general ESS plugin → imenu-anywhere

To be more specific, this is what it would boil down to:

- if a function is part of a package and we have TAGS for it, we jump to that one
- if not, we look in open files
- finally, we ask the R process for the source

Simple and nice.

**Comment by vspinu** [comment]
> Personally I think it makes sense to have this chain in R buffers: general ESS
> plugin → imenu-anywhere

Yes. As long as all of them are R specific and do what the top backend is
supposed to do, everything is fine.

> - finally, we ask the R process for the source

I don't think this is a good idea. There is C-c C-e C-d which is just for
that. No need to mix things up IMO.

**Comment by yitang** [comment]
@lionel- here is what I tried to build a TAG for multiple R packages.

```lisp
;; new variable 
(defvar ess-r-package-library-tags nil
  "A TAG file for multiple R packages.")

(setq ess-r-package-library-path '("~/tmp/feather/R" "~/tmp/RPostgres/"))
(setq ess-r-package-library-tags "~/tmp/all_tags")

(dolist (pkg-path ess-r-package-library-path)
  (let ((pkg-name (ess-r-package--find-package-name pkg-path)))
    (unless (and pkg-name pkg-path
		 (file-exists-p (expand-file-name ess-r-package-root-file pkg-path)))
      (error "Not a valid package. No '%s' found in `%s'." ess-r-package-root-file pkg-path))
    (ess-build-tags-for-directory pkg-path ess-r-package-library-tags)
    ))
```

The problem is it only builds TAGs for C/C++ code. Do you know why? I
can't figure out.

**Comment by lionel-** [comment]
I don't know how that code works. So I would try to step through `ess-build-tags-for-directory` with edebug and see what it does.

**Comment by vspinu** [comment]
That code is using etags and builds regexp based on current `imenu-generic-expression`. If no `imenu-generic-expression` was found then it is used as a regexp to etags. 

Let's write a new function for ctags. I also think we can actually build two tag files, one with internal R tagger (`ess-build-tags-command`) and one with etags/ctags whichever is available on the system. Then we merge the two tag tables.

**Comment by lawremi** [comment]
It's worth considering gtags here, because it also indexes the references, so it's easy to see all the places where a function is called. I wrote an R plugin for GNU Global, and embedded GNU Global + plugin into an R package (rgtags), so it's self-contained. It uses the actual R parser and is smart enough to handle all of the complexities of R, including S4 classes and methods. If this is of interest I can invest the effort in getting it past the lawyers at my company.

Things work great using rgtags and Emacs ggtags package, except I often get temporary freezes with the message "error in process sentinel: Customise alist is not specified, nor  ess-local-customize-alist is set", which obviously comes from `ess-mode`. I guess somehow ggtags is causing that function to be called from an incorrect context? Any ideas how to fix it?

It would be great to integrate rgtags with `ess-build-tags-command`. The problem is that the R plugin only works from within a running R session (i.e., when driven from R via the native interface), so it is not as simple as calling the command-line program. But this should not be a real problem for ESS, since it has access to R sessions.

On the front-end side, it's important to get namespaces right. Not just when using `package::` but ESS should parse the NAMESPACE file and/or use the associated R process to get the search path right. This would obviously be a requirement if the indexes are per-package. The xref package does look like a clean framework for this.

**Comment by fikovnik** [comment]
Does the R `rtags` work for you? If I use it I only get the first name of the functions (tokens). In both `list-tags` and in helm it is not much usable. I changed the `shorten.to.string` to return the full line and now it is much better.

Do I miss something?
