### ISSUE TITLE
debug_pipe() break points not working

### ISSUE THREAD

**Issue by uhkeller** [emacs-ess/ESS#325]
This is a variation on the problem reported in [issue 178](https://github.com/emacs-ess/ESS/issues/178), but using the function `debug_pipe()` from package magrittr. Unfortunately, the workaround offered by vspinu for the original problem does not seem to work here, or at least I don't see how it would have to be modified to make it work. 

Here's an example:

```
library(magrittr)
library(dplyr)
iris %>%
  group_by(Species) %>%
  debug_pipe() %>% 
  summarize(mean(Sepal.Length))
```

When I eval the above, the browser prompt is printed, but execution continues without pause:

```
Browse[1]> 
Source: local data frame [3 x 2]

     Species mean(Sepal.Length)
      (fctr)              (dbl)
1     setosa              5.006
2 versicolor              5.936
3  virginica              6.588
```

**Comment by vspinu** [comment]
Thanks. Fixed now. 

@lionel-  Is there now a way to detect that we are in magrittr pipe block? 

I would like to be make `C-c C-t b` to automatically set the correct breakpoint type there.

**Comment by uhkeller** [comment]
Wow. Can confirm that it's working now. Thanks!

**Comment by vspinu** [comment]
I will be pushing a new change in a moment. 

You can now set pipe breakpoints interactively and they are smarter than `debug_pipe` because you are placed into the data environment directly. That is, you can play with Species Sepal etc  at debug prompt or inspect with `C-c C-d C-e` directly in the pipe block. 

I am finally starting using pipe because of this!!

![debug_pipe](https://cloud.githubusercontent.com/assets/1363467/14782720/46f274c4-0aeb-11e6-8211-dec6eeda2a14.png)

**Comment by lionel-** [comment]
Nice. By the way the next version of magrittr will feature a complete refactor to make the evaluation simpler (in particular the tracebacks will be much cleaner). So this will probably have to be adapted.

**Comment by lionel-** [comment]
> So this will probably have to be adapted.

Scratch that, I was just making wrong assumptions about how this is implemented.
