### ISSUE TITLE
ess-eval-region in package directory failing until package is available

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#335]
Perhaps related to #334, but this time in R-3.2.5 and _not_ R-3.3.0.

Behavior in R-3.2.5:
1. Edit a source file in an R-package directory. Ensure the package is neither _installed_ nor _loaded_ (via `dplyr::load_all`, for instance). Completely unavailable to R (at the moment).
2. Highlight _any code_ (that does not load the package). Eval it (e.g., `C-c C-r`).
   
   ```
   Error in library(package, character.only = TRUE) : 
     there is no package called 'mypackage'
   ```
   
   The highlighted code is not executed.
3. `ess-eval-line-and-step` works without this problem.
4. If I load the local package into R with any method other than `ess-eval-region` (e.g., `ess-eval-line-and-step` or manually), all subsequent uses of `ess-eval-region` work without a problem.

Behavior in R-3.3.0: no error, works as expected.

(I believe the elisp is silently trying to load the package and its dependent namespaces into to the current R session. I make this inference on the fact that the first time I use `ess-eval-region` (in R-3.3.0 for this example), it lags a small moment and I get package-loading messages (e.g., masked functions). The second and subsequent evals do not lag.)

**Comment by vspinu** [comment]
> Behavior in R-3.3.0: no error, works as expected.

This is unexpected. Why different versions of R behave differently on this occasion?

I guess the best way to go about this bug is to simply assign everything in GlobalEnv when no package is available.

**Comment by r2evans** [comment]
I don't know the elisp enough to weigh in, but it should suffice as long as the "package is available" test is done for *each* use of `ess-eval-region`. For example, the first time I do it (in this particular script) is to test `require` and, if false, call `load_all` which then makes the package available. Once that block is complete, the package is available and all subsequent calls should work as designed.

**Comment by vspinu** [comment]
> call `load_all` which then makes the package available. 

This is a reasonable and consistent proposal, but there are people who are not using devtools and our code injection doesn't not rely on devtools either.

**Comment by r2evans** [comment]
Sorry, I wasn't clear. I was highlighting how my workflow impacted things in the context of your suggestion of *"assign everything in GlobalEnv when no package is available"*. Since the "package is (not) available" check is done for each call to `ess-eval-region`, your suggestion seems to makes sense. I wasn't implying that you should call `load_all`.

**Comment by chiraganand** [comment]
Hi, I am also facing this issue while working on an in-house R package. The issue goes away if I install the package. But since I am debugging the package functions, I don't want to taint my environment by loading it, but ESS load it by itself when I do C-c C-n.

Is there any workaround to this apart from copying-pasting to the ESS shell?

**Comment by ShuguangSun** [comment]
R 3.4.2, I have the same issue with the default setting.

It seems due to tracebug which requires run in namespace. However, the R can't find the pkg namespace because there is no "pkg" installed. When I disable tracebug, ess-eval-region works.

**Comment by vspinu** [comment]
I was bitten by this a couple of time as well. With the reasonably new version of ESS you can do C-c C-t C-s and set package to *none*. It's the R-package mode. I think a reasonable way to go about it would be to disable in-namespace evaluation if there is no such package in the system.

**Comment by MilesMcBain** [comment]
I'm on 17.11 and cannot use the evaluation environment *none* properly. I can set this as described above but the setting won't stick, it seems to flip back everytime I evaluate a function definition.

**Comment by vspinu** [comment]
Which mode is this R-mode? Could it be that something re-initializes the
mode in your buffer?


The variable `ess-r-evaluation-env` is set by C-c C-t C-s. So unless
something resets it, it should work. Can you check the value of that
variable in your buffer?

**Comment by MilesMcBain** [comment]
Okay there's a couple of things I discovered that are going on here:

I didn't realise the variable was buffer local - I had assumed it was global. I'm new to Emacs/ESS coming from RStudio so this seemed natural.
    * I think this lead to me assuming the variable wasn't sticking as I hopped around between different files.

There's some broken interplay between the eval env value in the current buffer vs the inferior REPL. Right now I have a file buffer with the eval env set to `nil`, which is the value it took after I set it to `none` using `ess-set-r-evaluation-env`. However, the REPL still has the eval env set to my not-yet-installed package. I cannot pass functions to the REPL to evaluate them without hitting the `there is no package called ...` error. So I set the REPL eval env in the same way and it works. 

However, I discovered a bug I can reproduce where this does not work if I set the REPL eval env first. To reproduce:
1. Start with a file buffer and an inferior REPL buffer both set to the not-yet-installed package - `testpkg`.
2. Run ess-set-r-eval-env from the REPL buffer and enter `none` when prompted.
3. Try to evaluate a function def from the file: `There is no package called testpkg`
4. Run ess-set-r-eval-env from the file buffer and select the first offered suggestion `*none*`
5. Try to evaluate a function def from the file: `There is no package called `none`.
When I inspect `ess-r-eval-env` in both buffers it is `nil` in the file buffer but `none` in the REPL buffer.

NOTE: I am using Spacemacs with Helm. I don't know enough about Emacs to know if this is relevant or not.

**Comment by pauljohn32** [comment]
I see this same issue today while working on my package called "stationery".  It was fine yesterday, so this is bizarre.  I've been trying to get better at org mode lately and I have updated the org-compat package from ELPA within the last week.  That's the only Emacs (Ubuntu 25.2.2, ESS 17.11) change I can think of.

If you point me at instructions on the ESS pulldown menu for Bug Reports, I would try it.  

All I did (transcript paste below) was open the package file, then ran library(stationery) to load the package literally,  then C-c C-c in a package function after editing it.  Then the problem happened, "there is no package ...". 

I found that by turning off tracebug makes it go away. I mean, then I'm able to C-c C-c to read in a function.

transcript

`> library(stationery)

## Here I try C-c C-c in a package function
> 
+ . + Error in library(package, character.only = TRUE) : 
  there is no package called ‘stationery ’
> 
+ . + Error in library(package, character.only = TRUE) : 
  there is no package called ‘stationery ’
>  compileme <- function(x, verbose) {
+         if (length(grep("\\.lyx$", tolower(x)))){
+             ## Let lyx compile to pdf
+             cmd <- paste("lyx -e pdf2 ", x, if(!verbose) sysnull)
+             if (isWindoze) shell(cmd) else system(cmd)
+             fnpdf <- gsub("\\.lyx$", ".pdf", x, ignore.case = TRUE)
+             if(tangle){
+                 ## Remove previous R file, avoid confusion
+                 unlink(gsub("\\..*$", ".R", x))
+                 ## lyx can directly export r code from knitr engine file 
+                 if (tolower(engine) == "knitr"){
+                     cmd <- paste("lyx -e r ", x, if(!verbose) sysnull)
+                     if (isWindoze) shell(cmd) else system(cmd)
+                 } else {
+                     ## will fail if split=TRUE, so must make copy of file, change to split=FALSE
+                     ## Need to turn split to FALSE in order to Tangle the lyx file.
+                     bak <- "-uniquebackupstring"
+                     fnbackup <- gsub("(.*)(\\..*$)", paste0("\\1", bak, "\\2"), x)
+                     file.copy(x, fnbackup, overwrite = TRUE)
+                     rnwfile <- readLines(fnbackup)
+                     ## Find SweaveOpts line, change split to FALSE
+                     rnwfile[grep("SweaveOpts", rnwfile)] <- gsub("(split\\s*=)\\s*.*,", "\\1FALSE,",
+                                                                  rnwfile[grep("SweaveOpts", rnwfile)])
+                     ## sets the prompt at ">"
+                     rnwfile[grep("prompt", rnwfile)] <- gsub("prompt\\s*=.*\"", "prompt=\"> \"",
+                                                              rnwfile[grep("prompt", rnwfile)])
+                     writeLines(rnwfile, con = fnbackup)
+                     cmd <- paste("lyx -e r", fnbackup, if(!verbose) sysnull)
+                     if (isWindoze) shell(cmd) else system(cmd)
+                     gg <- file.copy(gsub("\\..*$", ".R", fnbackup),
+                                     gsub(bak, "", gsub("\\..*$", ".R", fnbackup)),
+                                     overwrite=TRUE)
+                     if (file.exists(gsub("\\..*$", ".R", x))){
+                         unlink(paste0("*", bak, "*"))
+                     }
+                 }
+             }
+             if(verbose){
+                 if (tolower(engine) == "knitr"){
+                     cmd <- paste("lyx -e knitr ", x, if(!verbose) sysnull)
+                     if (isWindoze) shell(cmd) else system(cmd)
+                 } else {
+                     cmd <- paste("lyx -e sweave ", x, if(!verbose) sysnull)
+                     if (isWindoze) shell(cmd) else system(cmd)
+                 }
+             }
+         } else if (length(grep("\\.rnw$", tolower(x)))) {
+             if (tolower(engine) == "knitr"){
+                 if(tangle) knitr::knit(x, quiet = !verbose, tangle = tangle, envir = envir,
+                             encoding = encoding)
+                 fnpdf <- knitr::knit2pdf(x, quiet = !verbose, envir = envir,
+                             encoding = encoding)
+             } else {
+                 utils::Sweave(x, quiet = !verbose)
+                 if (tangle) {
+                     rfile <- tangleSplit(x)
+                 }
+                 fnbase <- gsub("\\.Rnw$", "", x, ignore.case = TRUE)
+                 fntex <- gsub("\\.Rnw$", ".tex", x, ignore.case = TRUE)
+                 ## if (!isWindoze){
+                 ##      tools::texi2pdf(fntex,
+                 ##                      texi2dvi = "texi2pdf", clean = clean,
+                 ##                      quiet = !verbose)
+                 ## } else {
+                 cmd1 <- paste0("pdflatex -interaction=batchmode \"", fntex, "\" ", if(!verbose) sysnull)
+                 out1 <- sysrun(cmd1)
+                 cmd2 <- paste0("bibtex \"", fnbase, "\" ", if(!verbose) sysnull)
+                 out2 <- sysrun(cmd2)
+                 out3 <- sysrun(cmd1)
+                 out4 <- sysrun(cmd1)
+                 ##}                       
+                 if(clean) unlink(fntex)
+                 fnpdf <- gsub("\\.Rnw$", ".pdf", x, ignore.case = TRUE)
+             }
+         }
+         
+         if (file.exists(fnpdf)){
+             return(fnpdf)
+         } else {
+             return("Failed")
+         }
+     }
`

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0
