### ISSUE TITLE
MELPA-stable release

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#356]
Just an FYI - it looks like the melpa-stable release is lagging behind. As I understand ESS 16.04 is the most recent available from ESS's website, but the latest tag on github is 15.9.

**Comment by mmaechler** [comment]
Don't know how this can be an issue with ESS.  ESS takes its version from the top-level VERSION file and that has been set to 16.04 for about three months now.

**Comment by jabranham** [comment]
MELPA-stable takes the info from git tags if I'm not mistaken. You can see the previous ESS releases were tagged: https://github.com/emacs-ess/ESS/releases

I think that what needs to happen is to find whatever commit the 16.04 released represents and tag it as v16.04

**Comment by mmaechler** [comment]
you are right.   The procedure should happen as part of   `make rel`   (which contains the `tag` target), but somehow that command line  git tag ... &  git push ... did not work (again!).   Happy for suggestions to fix the Makefile for next time.   I did tag 'v16.04' now via the github web interface.... Not what I wanted... but the issue is closed now.

**Comment by vspinu** [comment]
I was tagging releases manually, but forgot to do so last time :(

**Comment by mmaechler** [comment]
On Fri, Aug 12, 2016 at 11:23 AM, Vitalie Spinu
<notifications@github.com> wrote:
> I was tagging releases manually, but forgot to do so last time :(

but I really really prefer that this happens directly  i.e.,
"scripted"  from the release procedure... and  thanks to your
forgetting, and Alex' contribution,
it hopefully will now work automatically!

Thank you (both!),
Martin
