### ISSUE TITLE
unused argument error in ess.eval when using remote host with org-mode

### ISSUE THREAD

**Issue by DJJ88** [emacs-ess/ESS#366]
Hello,

I'm not sure I'm in the right place but I've encountered an error when using R on a remote computer.
I'm using org-babel to send some code on a remote computer. 

my emacs version is 24.4.1
org-version  8.3.5
ess-version: 16.04 [elpa: 20160905.653]

#+BEGIN_SRC R :results value  :dir /ssh:gnu:/home/livelygnu/Documents/R/ :session *R1*
mean(1:30)
#+END_SRC

#+RESULTS[0d3805c1762b93afafe96d0ac607d5ae51c62a27]:

the above commands produce the following error
Error in .ess.eval("mean(1:30)", visibly = FALSE, output = TRUE, file = "/tmp/unknown!20046Gwb") : 
  unused arguments (visibly = FALSE, output = TRUE)

Note: if I change the results header: :results output everything works fine.

Things seems to work fine on the localhost though
 
#+BEGIN_SRC R :results value  :session *R*
mean(1:30)
#+END_SRC

#+RESULTS:
: 15.5

**Comment by vspinu** [comment]
Could you please try again with melpa?

**Comment by DJJ88** [comment]
The version ess-version: 16.04 [elpa: 20160905.1519] works smoothly.
Many thanks to you.

**Comment by vspinu** [comment]
Ok. Considering it fixed. Thanks for the report.

**Comment by fkgruber** [comment]
Hello,
I't seems this bug is back? I'm having exactly the same issue when submitting code to a remote server. I using the latest stable release ESS: 18.10.2
orgmode version 9.2 org-plus-contrib-20181230
 When I tried to use :results value I get
Error in ss(file, echo = visibly, local = local, print.eval = output,  : 
  unused argument (spaced = FALSE)

it works fine with :results output and if the R is running local. Same behavior as initial poster.
