### ISSUE TITLE
Support for assignment with the equal sign =

### ISSUE THREAD

**Issue by rsuhada** [emacs-ess/ESS#370]
While I know this is somewhat controversial, could ess-mode support equal sign along `<-` for its functionality?  E.g. with imenu support etc. 
1. using `=` instead of `<-` decreases the cognitive costs immensely when one is forced to switch between the languages. 
2. The practical difference between the assignment signs is negligible as far as I know (the difference being that `<-` can assign within a function call - which sounds like a terrible idea anyway!).

Would it be possible for ess-mode to put `=` on equal footing with `<-`?
Thank you very much!

**Comment by vspinu** [comment]
You are not thinking about cognitive costs of seasoned R programmers who are used to `<-`. Your code makes all those people cringe.

**Comment by rsuhada** [comment]
I'm suggesting to add `=` along `<-`, not to replace it completely!
If somebody prefers it, of course he/she should be free to continue to use it.

**Comment by lionel-** [comment]
I think we should support it because it is part of the language, but I agree this is bad style and you're just transferring the cognitive costs, i.e. switching from one style to another while reading R code. This is arguably much worse than differences across languages since reading another language requires a cognitive switch anyway.

**Comment by jabranham** [comment]
I added imenu support for this, please open a new issue if you notice other areas where we aren't supporting the equals sign for assignment.
