### ISSUE TITLE
temporary solution for inferior-julia on windows

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#377]
I don't know if you guys want pull requests for this, but there was a partial solution for inferior julia on [windows](https://github.com/JuliaLang/julia/issues/5271) that can be adapted for ess-julia.  The current eldoc support doesn't work though, it hangs emacs.

repl_init.jl

```
using Base.Terminals: UnixTerminal
using Base.REPL: BasicREPL, run_repl

type PipeTerminal <: UnixTerminal
    in_stream::Base.IO
    out_stream::Base.IO
    err_stream::Base.IO
end

run_repl(BasicREPL(PipeTerminal(STDIN,STDOUT,STDERR)))
```

elisp code

```
(when (and load-file-name (eq system-type 'windows-nt))
  (setq inferior-julia-args
        (format "-i -L%s" (expand-file-name "repl_init.jl" "path/to/directory"))))

;; disable eldoc for `julia'
(defadvice julia (around disable-eldoc activate)
  (let (ess-use-eldoc)
    ad-do-it))
```

**Comment by jabranham** [comment]
@nverno is this still needed or can we close this issue? I don't use julia much or Windows at all.

**Comment by nverno** [comment]
Me neither, I haven't used Windows in a couple years. Julia has changed a lot, I'd close it until someone has the issue.

**Comment by r2evans** [comment]
I'm just coming to this thread and ask either that it be re-opened or perhaps include some pointers to fixing things.

Situation: win10, emacs (from https://github.com/vigou3/emacs-modified-windows/releases), ESS-20180922.2254, julia-mode-20180816.2117, and Julia-1.0.0. Start `M-x julia`, emacs hangs; no surprise `C-g` gets me to a prompt-less julia interface, where I can still type julia commands and get answers but get no prompts and therefore why ESS is having difficulty. This is confirmed in `M-x shell` and `M-x eshell`: no banner, no prompt. Odd, though, `Sys.isinteractive()` is true, and even when I force `export TERM="dumb"` before calling it, I don't get the warning (in `Client.jl`) saying that the terminal is not well supported. So something further is happening.

Trying the code listed above (from 2016), I get several errors. Changing the top two lines to:

```
using REPL.Terminals: UnixTerminal
using REPL: BasicREPL, run_repl
```

works for them (I'm not certain that this is correct, mind you, rather new to Julia). But the next line produces

```
ERROR: syntax: extra token "PipeTerminal" after end of expression
```

Thoughts?

**Comment by nverno** [comment]
I don't think `type` is the proper syntax anymore, probably `primitive type`. A lot of the other stuff has been moved around, like `STDIO`, etc. are in different places now as well.

**Comment by vspinu** [comment]
This looks like a question for julia tracker. We wouldn't know.

**Comment by r2evans** [comment]
@vspinu @nverno My gratitude. Yes, certainly. I had read through several other ESS issues here -- where you are repeatedly saying that this is not ESS -- before posting on this one. Many of the discussions are a year or more old, though, suggesting that this could have been remedied in Julia-1.0.0.

I was hoping somebody else would see this and be able to cross-post to a more-recent relevant discussion about it. It's awesome to me that ESS works flawlessly with Julia on linux ... and perplexing that emacs/win fails so miserably with it. (I think it's fair to say that this is as much an emacs/win issue as a Julia issue, since emacs terminal emulation is certainly complex and not without other issues.)

My panacea: ESS works with all languages that ***I*** use (R, Python, learning Julia). I know it's selfish, but my muscle-memory is what it is. (Funny ... on my surface book, I moved `Ctrl` to my caps-lock key due to this muscle-memory thing ... and my caps-lock key has split/broken due to its overuse. I literally have medical tape on the key to hold the pieces together, pad my finger a little, and allow the continued use of my "ctrl". Does that make me a `Ctrl`-freak? :-)

Thanks for all of your work on ESS!

**Comment by davenamin** [comment]
not to resurrect a dead issue, but the following works for me on Windows with Julia 1.0.2 (as the contents of `repl_init.jl` in the original comment)

```
using Base: stdin, stdout, stderr
using REPL.Terminals: TTYTerminal
using REPL: BasicREPL, run_repl

run_repl(BasicREPL(TTYTerminal("emacs",stdin,stdout,stderr)))
```
