### ISSUE TITLE
lib.fixup invisible from .load.R if R_ENABLE_JIT=3

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#384]
If I start R with R_ENABLE_JIT=3, then I got an warning:

load ESSR: + + + Note: no visible global function definition for ’lib.fixup’ 
Note: no visible global function definition for ’lib.fixup’ 

It starts from year ago. My current evironment:
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Emacs version: GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-22

**Comment by mmaechler** [comment]
The warning is just a  __note__., right?   
It is because our R code is written in a way to also work with very old versions of R; in those R versions, the 
lib.fixup had been defined and was *the best* way to do something close to attaching an environment to the `search()` path.   The warning happens because that part of the code cannot be compiled, because the compiler is from today's R, and that part of the code is never executed in today's R, where only the simple  `r attach(ESSR)`  is sufficient:
```r
   if(Rver >= "2.4.0")
        attach(ESSR)
    else if(!oldR) { ## borrow from older library()
        e <- attach(NULL, name = "ESSR")
        .Internal(lib.fixup(ESSR, e))
    } else { ## if(oldR), use as in that old library():
        .Internal(lib.fixup(ESSR, .GlobalEnv))
    }
```
I hope you can live with that for the moment.
In an ideal world, we could  tell the compiler *not* to try compiling that whole part of the function.

**Comment by ShuguangSun** [comment]
Yes. Thanks for the great work of ESS team.

**Comment by mmaechler** [comment]
There's another environment variable to **suppress** compiler warnings.  So set this in the same place you set `R_ENABLE_JIT` :
```
R_COMPILER_SUPPRESS_ALL=yes
```
