### ISSUE TITLE
ESS does not load with Emacs 25.1.1 under Ubuntu

### ISSUE THREAD

**Issue by renkun-ken** [emacs-ess/ESS#392]
Previously, I use ESS with Emacs 24 under Ubuntu 16.04 and it works. Due to some DNS resolution bugs in emacs 24 dependencies which caused ESS startup script to hang, I have to upgrade to Emacs 25 through PPA (http://ppa.launchpad.net/adrozdoff/emacs/ubuntu). However, after installing ESS through `apt-get`, Emacs 25 does not seem to recognize anything about ESS and the startup script does not run.

**Comment by mmaechler** [comment]
Please be more specific.  How did you install ESS?   As debian/ubuntu package emacs-ess?
If yes, then by "manual" upgrading to emacs 25 (instead of using the "official" ubuntu emacs version), you may have lost the ubuntu automatism of loading ESS.
But it should be easy to load ESS yourself, following the ESS instructions, notably trying to

   (require 'ess-site)

in your ~/.emacs  (which you may have to create if it does not exist).
Yes, this will only activate ESS for you, i.e., not all users... but it at least should get you going.
Can you report back?

**Comment by renkun-ken** [comment]
I added `http://ppa.launchpad.net/adrozdoff/emacs/ubuntu` to my sources and `sudo apt install emacs25` and then `sudo apt install ess`. But when I start emacs with an R script, ESS is not automatically loaded.

I'll try activating ESS myself.

**Comment by renkun-ken** [comment]
I added `http://ppa.launchpad.net/adrozdoff/emacs/ubuntu` to my sources and `sudo apt install emacs25` and then `sudo apt install ess`. But when I start emacs with an R script, ESS is not automatically loaded.

I tried activating ESS myself by creating `~/.emacs` and write exactly as you suggested, but nothing happens.

**Comment by renkun-ken** [comment]
When I reinstall emacs24 along with 25, ESS suddenly works with 25.

**Comment by Currerius** [comment]
I had the problem after installing emacs 25.2 yesterday. ESS would not load. 
(require 'ess-site) 
did work for me. And I *really* needed an immediate fix. 
Thank you.

**Comment by jabranham** [comment]
This sounds to me like an ubuntu packaging bug, not an ESS bug. Either way, it's hopefully resolved by now. OK to close? @lionel-

**Comment by AlainPat1** [comment]
I experience the same problem with Win10: ESS and emacs24 worked fine together but as soon as I upgraded to emacs25.3.1, ESS was no longer recognized.  Edit > "Manage emacs package" indicates that ESS is no longer compatible "because it depends on uninstallable packages"

**Comment by jabranham** [comment]
@AlainPat1 do you have julia-mode installed? It's a dependency of ESS.

**Comment by AlainPat1** [comment]
"Julia-mode-0.3 (not available)" I have updated emacs to 25.3.1 (x86_64_w64_mingw32) on Win10 (downloaded from https://vigou3.gitlab.io/emacs-modified-windows/ ). When accessing the list of packages available, ess is listed as "Incompatible because it depends on uninstallable packages... Requires julia-mode-0.3 (not available)".
