### ISSUE TITLE
nil in load-history

### ISSUE THREAD

**Issue by tagteam** [emacs-ess/ESS#406]
with emacs 26.0.50.1 (or emacs 25.x) after loading ess (16.10-1 [elpa: 20170206.310]) via

```lisp
(use-package ess-site :ensure ess)
```

I get a value 'nil' in the load-history

```lisp
(mapcar 'car load-history)

"~/emacs-genome/genes/ess-20170206.310/lisp/ess-site.elc"
nil
"~/emacs-genome/genes/ess-20170206.310/lisp/ess-toolbar.elc"
"~/emacs-genome/genes/ess-20170206.310/lisp/ess-mouse.elc"
```

the 'nil' occasionally causes trouble, e.g., when `help--loaded-p` does this:

```lisp
(dolist (x load-history) (if (string-match-p re (car x))
(setq done t)))
```

**Comment by mmaechler** [comment]
Note that  `(use-package .)` is not in my emacs 25.x, but the same phenomenon appears when using
`(require 'ess-site "<path-to-ess>/lisp/ess-site.el")`    after starting "vanilla emacs"  (=  `emacs -Q`).

**Comment by jabranham** [comment]
Do you still experience this? I can't seem to reproduce it using today's ESS.

**Comment by tagteam** [comment]
yes, I still have it to after upgrade to 2018-04-26:

(mapcar 'car load-history)
...
"/home/tag/emacs-genome/genes/ess-20180426.1302/lisp/ess-site.elc" nil "/home/tag/emacs-genome/genes/ess-20180426.1302/lisp/ess-toolbar.elc"

but, yesterday was the 2nd of May. where can I get this version? thanks!

**Comment by vspinu** [comment]
Yes, please. It's a very good idea. That buffer pasting and evaluation is just an R-programmer doing lisp :)

**Comment by vspinu** [comment]
How about `ess-r-create-runner` instead of `ess-r-create-version`?

**Comment by jabranham** [comment]
Yeah, the name is gross. `ess-r-create-runner` is better. 

It's not immediately clear to me how `inferior-R-version` actually tells the `R` function which binary to call. Do you happen to know that off the top of your head?

On a somewhat-related note, can we rename `R` to something like `ess-run-R` and alias `R` and `run-R` to it? Sometimes when I'm testing out functions I do something like `defun R` as a placeholder (while not thinking about R/ESS), which is annoying since I then have to go find the ESS R function again. 

And other builtin modes define `run-python`, `run-octave`, `run-dig`, etc, so we might as well define `run-R`. 

If that's OK, I can submit a separate PR.

**Comment by vspinu** [comment]
> It's not immediately clear to me how inferior-R-version actually tells the R function which binary to call. 

AFAICS it's used once in inferior-ess--maybe-prompt-startup-directory for prompt only and has not function otherwise.  I think a lot of those R-version variables are not named aptly. If you could have a look at those and clean/simplify the code on this occasion would be truly great.

> On a somewhat-related note, can we rename R to something like ess-run-R and alias R and run-R to it? 
> And other builtin modes define run-python, run-octave, run-dig, etc, so we might as well define run-R.

This sounds reasonable. A lot of ESS code precedes those emacs conventions btw.

**Comment by jabranham** [comment]
> If you could have a look at those and clean/simplify the code on this occasion would be truly great

I'll take a look, but will submit a separate PR since it's not directly related. 

> This sounds reasonable. A lot of ESS code precedes those emacs conventions btw.

Great, PR submitted. And yes, I know ESS is older than a lot of more modern conventions :-) 

Thanks!
