### ISSUE TITLE
ess-microsoft-p in ess-compat.el

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#408]
The def of ess-microsoft-p should be 
`
(defvar ess-microsoft-p (memq system-type '(ms-dos windows-nt))
  "Value is t if the OS is one of Microsoft's, nil otherwise.")
`
instead of 
`
(defvar ess-microsoft-p (memq system-type '(ms-dos 'windows-nt))
  "Value is t if the OS is one of Microsoft's, nil otherwise.")
`

**Comment by mmaechler** [comment]
Don't know which version of emacs you are using, but the above has not been part of the sources since
#3aa213cf (Vitalie Spinu    2015-07-02)   which is quite a long time ago and you must be using a pretty outdated version of ESS.
While that is not your fault at all, you only should report issue *after* updating {or reading the current source code}.

**Comment by mmaechler** [comment]
I've accidentally closed this because my own working copy of ESS was not uptodate.  Yes, this is an obvious  typo / thinko.. and will be fixed ASAP.
