### ISSUE TITLE
*shell* buffer in ESS "package mode"

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#466]
Not a killer bug; but still awkward and a bit embarrassing:

After having looked a bit at CRAN package `diceR` (a test of which was a bit fishy and failing in R-devel only).... The modeline in *shell* mode is showing as if it was an R buffer in "package-mode", see screen shot [at SfS ftp](ftp://stat.ethz.ch/U/maechler/ESS/screenshot_Emacs_shell_pkg-mode_2017-11-25.png)... Ok, ftp fails; using [Dropbox](https://www.dropbox.com/s/3pqcg6rx0vm6kmk/screenshot_Emacs_shell_pkg-mode_2017-11-25.png?dl=0)

**Comment by lionel-** [comment]
Maybe there should a variable taking a list of major modes where `ess-r-package-mode` should be enabled? But that could be extensive (C/C++, javascript, html, markdown, rust, makefile, fundamental, ...). So maybe a list of major modes where it shouldn't be enabled?

**Comment by mmaechler** [comment]
Good idea ... for the first :  a default "--include" list.  After all I'd rather see this for R sources.
A process buffer as  *shell*  in this issue should rarely be in this mode unless it is the R console, no?

**Comment by lionel-** [comment]
I think an exclude list might be preferable. If you open a file within a package chances are that you want the minor mode enabled so you have access to package commands (install, test, check, ...).

**Comment by vspinu** [comment]
Why is the current behavior problematic more concretely? I do see myself
running test, install etc actions even from shell buffers when within R
projects. R pkg mode is for working on R package and is (by design)
accessible from all buffers related to that package.

**Comment by lionel-** [comment]
IIUC Martin, the fact that you can `cd` out of a package with the shell buffer and stay in package mode is a bit strange. I don't think it's necessarily bad though.

**Comment by mmaechler** [comment]
@lionel- yes, a `*shell*` buffer has many purposes;  even if I may have opened it (via my simple key stroke) when I had been inside some package file/dir,  the buffer may have and typically does not have any relevance to where I opened it from.   ESS behaves very intrusively from my point of view by "owning" that shell buffer.   Good citizens do not do that.

**Comment by lionel-** [comment]
I think the good citizen thing is a bit of an exaggeration because you've opened that shell from a package file after all. It's also easy to kill the shell buffer and reopen one elsewhere. Vitalie has a point that opening shells within a package is a normal part of a development workflow, so I'm not sure what's best here.

**Comment by mmaechler** [comment]
I've opened it with my key stroke -- in the quickest way possible, because I want do something in the shell ... this ABSOLUTELY unrelated to R or ESS....  ESS should not declare buffers belong to it, just because I happen to have an R/ESS buffer open when I start to quickly do something because someone calls me on the phone or walks in my office or ...  ((dear me))

**Comment by lionel-** [comment]
Enabling a minor mode is hardly declaring ownership. There's plenty of ways to disable this already (e.g. using the minor mode hook). I'm not opposed to having a list of major modes where it shouldn't be enabled, but I'm still wondering what's the good default if we introduce such a list.

**Comment by vspinu** [comment]
> I'm not opposed to having a list of major modes where it shouldn't be enabled,

I want it in all buffers where `default-directory` is a child of an R package and I expect that to be a common use case. So I am strongly for "exclusion" variable instead of the "inclusion" one.

> but I'm still wondering what's the good default if we introduce such a list.

It's trivial indeed. Just disable `ess-r-package-mode` in shell mode.  

> ESS should not declare buffers belong to it  just because I happen to have an R/ESS buffer open 

It's a minor mode as any of the dozens of minor modes active at the same time. It attaches for all buffers with default directory being a sub-directory of an R package. No R/ESS buffer needs to be open. 

We do display in minibuffer, but that's a minor.  The only real issue with our `ess-r-package-mode` is that its `C-c C-w` binding can interfere with some other major modes, but I doubt there is a good solution for that. 

> ABSOLUTELY unrelated to R or ESS...

If someone opens a shell inside an R package it's more likely that its related to the R package development than the other way around. Deactivating this minor mode because on rare occasions one does something unrelated doesn't make much sense because the mode is non-intrusive (besides the C-c C-w keybinding of course).

**Comment by lionel-** [comment]
> It's trivial indeed. Just disable ess-r-package-mode in shell mode.

Maybe dired as well?

**Comment by mmaechler** [comment]
Doesn't sound bad, use such an exclusion list, and start by adding  shell- and dired-mode.  
That would settle this issue fine for me.

**Comment by vspinu** [comment]
I don't think this should be the default. Such exceptions are unexpected and complicate user API.

**Comment by lionel-** [comment]
Still needs a variable to configure it.
