### ISSUE TITLE
flymake: filename as args for ess-r--flymake-proc and wrong rx for flymake-parse-output

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#555]
Windows 7
Emacs 27
R: 3.5.0

In the ess-r--flymake-proc of ess-r-flymake, the lintr::lint requires filename, e.g., buffer-file-name, as argument, but not the buffer-string. 

In the ess-r--flymake-parse-output, the "<text>:" of the rx will not be matched, as the outputs from lintr::lint begins as filename:row:col: .... 
It works to replace as (minimal-match (one-or-more not-newline)) ":"

**Comment by vspinu** [comment]
I think you still need the newest github version of lintr. I am a bit surprised it's still not on CRAN.

**Comment by jabranham** [comment]
They are working towards a new CRAN release.

**Comment by mmaechler** [comment]
I see that  `flymake` seems active by default in ESS now?  At least it is on one of my Linux computers, and there it is a pain:  I use a large "emacs-desktop" (which re-loads a few hundred of my recently used emacs buffers (dired and files)).   Many of these are related to R,  and with Emacs 26 (new on that computer) my desktop loading takes ages (not least because it produces a warning for every *.R file that it does not find something like 'flymake-init'...

I'm tending to ask this to be made optional (which it probably is) and off by default but maybe you have discussed this before?  Is "lintr" or similar nowadays "on" by default in Rstudio ?

**Comment by jabranham** [comment]
> I see that flymake seems active by default in ESS now?

Yes it is

> my desktop loading takes ages

Yes, that does sound annoying. Ideally this would be fixed by Emacs upstream. I could see flymake using the new threads in Emacs 25 (or was it 26?) to check things asynchronously. But obviously you're looking for a solution now, so that won't help.

> I'm tending to ask this to be made optional (which it probably is) and off by default but maybe you have discussed this before? Is "lintr" or similar nowadays "on" by default in Rstudio ?

I believe lintr is active in rstudio by default. 

If you don't like the linting, you can disable it with `(setq ess-use-flymake nil)`, which you'd want to do before letting Emacs reload your desktop files. 

I'd prefer to keep flymake on by default, since I think it's easier for people to turn off features they don't like than discover potentially useful features they don't know about. I'll look around to see if there's some way to either speed up spawning the subprocess(es) and/or delaying their start.

**Comment by lionel-** [comment]
> I'd prefer to keep flymake on by default, since I think it's easier for people to turn off features they don't like than discover potentially useful features they don't know about.

It's also easy to be inconvenienced forever when you're not sure what is causing your troubles ;)

I just installed the lintr package to try this new feature. First impression is that it causes lots of flickering in the modeline. Could that be avoided?

**Comment by jabranham** [comment]
> It's also easy to be inconvenienced forever when you're not sure what is causing your troubles ;)

True. There's always tradeoffs I suppose. 

> I just installed the lintr package to try this new feature. First impression is that it causes lots of flickering in the modeline. Could that be avoided?

I haven't seen this. In fact, I can't recall ever seeing the modeline "flicker" (in ESS or elsewhere) Can you be more specific?

**Comment by lionel-** [comment]
I'm seeing `Flymake[0 0]` flick to `Flymake:Wait[0 0]` when I type.

**Comment by jabranham** [comment]
Ah, OK. Yes, that's normal and expected. It's flymake updating the modeline to let you know it's "working" (i.e. it's running  the R subprocess and awaiting results). 

It looks like that's controlled by `flymake--mode-line-format` and doesn't allow much customization currently.

**Comment by jabranham** [comment]
You can of course remove that entirely from the mode line. You'll still get the squiggly overlays in the buffer but won't get the total number of errors/warnings at the bottom.

**Comment by lionel-** [comment]
I can't get it to highlight anything. Can you give an example of bad code that should be highlighted?

**Comment by jabranham** [comment]
`x = 3`

it should complain about not using `<-` for assignment. 

You have to have the github version `devtools::install_github("jimhester/lintr")`.

**Comment by mmaechler** [comment]
Eehm.. but really, ESS should not depend on the github-version of a package!  Maybe turn flymake off not only if "lintr" is not available, but also `if(getVersion(package="lintr") < 1.1)`, please ?
I'm now almost sure that the 700 warnings I see on startup are also because I almost never install non-CRAN version of packages.

**Comment by jabranham** [comment]
I agree it's not ideal. The reason it depends on the github version is because Emacs sends the current buffer as a string to `lintr::lint()`. `lintr::lint()` only began accepting strings after the current CRAN release, it only accepted files before that. I thought it'd be better to send the current buffer rather than files for a few reasons: 1) we can check non-file-visiting buffers and 2) less chance of the contents on disk being different from the current buffer, which could result in flymake highlighting the wrong region.

Though I admit when I wrote it I thought they'd have a new CRAN release by now :-)

flymake disables itself in a buffer pretty quickly if it detects lintr version < 1.0.2 (current CRAN release is 1.0.1). We could add something that checks the lintr version when `ess-r-setup-flymake` is first loaded, I suppose...

**Comment by vspinu** [comment]
Yeh. It takes them a while to push the new release. It has been 8 months (at least) since the "string" feature  was implemented. 

I very much agree that features should be on by default even if they are annoying. Otherwise they become quickly dead code. But maybe in this case we can wait till next release and hopefully lintr will be finally pushed to CRAN by then. Checking for lintr version for every buffer is not an option because it requires sparking new process just for that. But maybe if we do it once per session it could still work.

An alternative might be to activate lintr only when there is an active R session connected. I find this to be a sane default for the following reasons. First, one often inspects foreighn package or a script and one doesn't care if there are lint "errors" there. All you care about is whether there are lint errors in packages (and maybe scripts) which you write. Second issue is that lintr is run in process which might not be the same process as the one current buffer is attached to. The "other" process need not even have lintr installed. Think of @mmaechler  with his 100+ R execs in the system. I would propose linting only when current session exists, checking for lintr in the current process and sparking lintr with the exact same R executable as the current process. This is actually a standard pattern for ESS, there is no eldoc or completion when there is no process.

Another alternative would be to run flymake only in the currently visible (working) buffer only and not in the background, but that cuts into `flymake`'s functionality and ideally should be part of `flymake` itself.

**Comment by mmaechler** [comment]
Thank you Vitalie @vspinu : Indeed, I open *many* R files in Emacs which I don't want to modify at all.  That is true for teaching (where I wouldn't want my audience to be bothered by the extras), or when inspecting other people's packages for various reasons, including when debugging (but not wanting nor even be allowed (read only) to change any code).   

This would really be the ideal behavior of flymake: Only get active when an R buffer is connected to an active R session !!

**Comment by jabranham** [comment]
I suppose we could implement that. Can we keep the current behavior as an option though? I tend to think of ESS lacking eldoc/completion until an R process starts as a bug rather than a feature. I'd prefer it if we could offer eldoc and completion even without the inferior process running, like many (most?) other major modes do.

**Comment by vspinu** [comment]
> Can we keep the current behavior as an option though? 

Of course. I would imagine there will be plenty of people out there wanting to have it all the time. We could have a range of options for this.

> . I'd prefer it if we could offer eldoc and completion even without the inferior process running, like many (most?) 

Certainly not most, not even many. Lisps  (elisp included) don't have static completion. For dynamic languages, static completion tends to be buggy and limited. Even the star of dynamic languages python struggles with it.

We could think of adding completion backend based on an existing tag table in the project directory, but benefits are marginal. Company does have a grouped backend for tags but the problem with that one is that it's never reached.

**Comment by vspinu** [comment]
To be frank I am growing increasingly unhappy with flymake. I don't find it that helpful and large amount of false positives and bugs in lintr is rather distracting. Different projects use different styles and because lintr rules (even with many by default disabled by ESS) are rather opinionated I end up with green highlight everywhere just because of the aggressive snake case rule. Asking users to configure linr on every single script they use is unnecessary burden.

So, instead of cutting down further rules I am now inclined to deactivate this feature till lintr is mature enough (at least till the new version is on CRAN) and not until we have a well thought list of different activation options in place. For now we could activate it automatically only in two cases, if there is a .lintr configuration file present or ess-use-lintr is non-nil. The latter could be set in a dir-locals.el. 

I think that given current situation this would be a better default at least for now.

**Comment by jabranham** [comment]
Another alternative is to deactivate by default all the style linters
leaving only those that indicate wrong code (i.e. return errors to flymake)

**Comment by vspinu** [comment]
Indeed. I guess we could leave all those which comply with the R printer.
