### ISSUE TITLE
with-eval-after-load 'ess-site stopped working

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#589]
```elisp
(with-eval-after-load 'ess-site
  ...)
```
stopped working as of today for me. I can replace `'ess-site` with `'ess-r-mode` and stuff works for R again, but not julia, `'ess-mode` does not work for both, is there a way to make this work for all `ESS` dialects?

**Comment by vspinu** [comment]
This is a consequence of recent MELPA adjustments. ess-site is no longer loaded and all functionality is autoloaded, as it should be.

Try `ess-utils`. It is loaded everywhere. 

Otherwise, quote your stuff with `(setq my-ess-config '(progn ...))`, then `(eval-after-load "ess-r-mode" my-ess-config)` and `(eval-after-load "ess-julia")`.

**Comment by gdkrmr** [comment]
works, thanks!
