### ISSUE TITLE
GPG signed releases

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#625]
ESS should probably provide GPG signatures for releases so that people installing from the tarball can be sure the tarball they received is the one we actually released. Given that many of our users are high-value targets (people with access to all sorts of data --- health info, financial information, etc), it would be a *bad thing* if attackers were to modify ESS since it can run arbitrary code.

As far as I know, there are no downsides to providing GPG signatures with release tarballs.

**Comment by vspinu** [comment]
I think we should sign git tags as well.

**Comment by vspinu** [comment]
I am labeling this for 18.09. I think it's important that our last tar before the major refactoring is signed. @mmaechler would you mind having a look?

**Comment by vspinu** [comment]
Ok, the initiative is great, but how do we do this in concrete terms? 

It's not much that I could find on embedded signatures. [swbis](https://www.gnu.org/software/swbis/sourcesign-1.2/gendocs/manual/sourcesign.html) is not even installed by default in ubuntu; this [SO](https://stackoverflow.com/questions/7183319/digitally-sign-tar-gz-file) says it's not possible. 

Let alone the embedded signature, in order to create a detached signature we would need our public key floating around. It should probably be Martin's public key if he has one or we should create a new public key for ess-core mailing address and let a few of us keep it. @mmaechler?

Generally speaking signing stuff requires good bookkeeping (safe and recoverable private key + revocation certificate). Unless someone here has working experience with that and is willing to maintain our archive signing and git tag signing we should probably pass for now.

**Comment by jabranham** [comment]
In concrete terms, it's as easy as adding `gpg --sign $(ESSDIR).tgz` to the `tarballs` target (and we'd need to add similar for the zipfile). That produces a file `ess-VERSION.tgz.gpg` that anyone can verify the signature of by doing `gpg --verify ess-VERSION.tgz.gpg`. 

Please don't create an ess-core gpg key; current best practice is for individuals to have a key and then cross-sign keys. There's a bit more here: https://www.kernel.org/signature.html

> Generally speaking signing stuff requires good bookkeeping (safe and recoverable private key + revocation certificate). Unless someone here has working experience with that and is willing to maintain our archive signing and git tag signing we should probably pass for now.

Yes, that's true. If no one here has a GPG key or wants to mess with this, I can take care of it. I use gpg. You can get my key by doing `gpg --keyserver hkp://pgp.mit.edu --recv-keys 7842785C03209625CD5E27291E4227A253E99AC7 `

**Comment by vspinu** [comment]
> it's as easy as adding gpg

Well, that's not an embedded signature which I thought you meant in the OP.

I am bringing this on the mailing list.
