### ISSUE TITLE
ess-julia-mode autoloads

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#645]
When julia is installed after ess, the autoloads aren't generated. Is there a way around wrapping the entire file in a condition clause?

**Comment by jabranham** [comment]
I also really don't like how ess-julia is handled. I suggest we either:

* Make julia-moded a dependency and just assume it's available or 
* Spin off ess-julia into its own package, which would have ESS as a dependency and live under emacs-ess github organization.

**Comment by nverno** [comment]
I wouldn't mind either of those options. The first seems like it would require much less work though, which is probably a major benefit. Then, in the future if needed it could be separated out?

**Comment by vspinu** [comment]
I completely missed that we don't have julia-mode dependency. Of course we should add that. 

Which autoloads are not generated? For julia-mode? The ess autoloads should all be there.

**Comment by nverno** [comment]
I might have tested incorrectly, let me try from fresh install. Also, I just installed Julia 1.0.0 and there appear to be issues with the ESS julia completion. Anyone else seen those issues?

**Comment by jabranham** [comment]
@vspinu  It's sort-of kind-of a dependency. Installing from MELPA, it's a dependency. But then we guard against this in the beginning of ess-julia (which makes for some strangeness when byte compiling) and it's not mentioned as a dependency anywhere in the docs. And the Makefile actually goes out and downloads julia-mode.el to include in the tarball.

**Comment by vspinu** [comment]
What do you mean by sort-of? I don't see it declared anywhere. It should be declared in ess.el. 

The fetching is for tarball and cannot be removed unless we drop other distribution channels beside ELPA.

@nverno Breakage are quite likely. If julia folks change the internals then things will break. We are entirely relying on users to fix those because none of the core ESS developers is using julia at the moment. See ess-julia.jl in the etc folder. It's usually trivial to fix with even basic knowledge of julia.

**Comment by nverno** [comment]
Ok, I don't get any autoloaded `ess-julia-mode` from a clean install from MELPA even when I install `julia-mode` prior to installing `ess`

**Comment by jabranham** [comment]
It used to be in ess-pkg.el, which got deleted about 2 months ago 36d4e2a319bc61fefe5b58046e66ea6db29dbc4b.

I think we still need ess-pkg.el, it's how multi-file packages should declare themselves `(info "(elisp) Multi-file Packages")`. 

> The fetching is for tarball and cannot be removed unless we drop other distribution channels beside ELPA.

Well, we'd just list julia-mode as a dependency in the installation/building ESS docs and let the distro maintainers package it separately. I don't think this is an issue at all.

**Comment by nverno** [comment]
So, this is the bare init file I was trying (deleting `julia-mode` and `ess` first)

```
(prefer-coding-system 'utf-8)
(require 'package)
(add-to-list 'package-archives
	     (cons "melpa" "https://melpa.milkbox.net/packages/"))
(package-initialize)
(package-refresh-contents)

;; assuming ess and julia-mode are deleted prior
(dolist (pkg '(ess julia-mode))
  (unless (package-installed-p pkg)
    (package-install pkg)))

(condition-case nil
    (ess-julia-mode)
  (error (message "ess-julia-mode not autoloaded")))

```

And calling `emacs -Q -L ~/.emacs.d/elpa/ -l ~/.emacs.d/etc/bare-julia.el`

**Comment by vspinu** [comment]
@jabranham people could install from git as well. We don't need ess-pkg.el for sure (at least for MELPA). It should work by adding into ess.el or ess-julia.el

@nverno, I don't see julia and ess-julia-mode autoloaded in my MELPA dir. Something is not right, but what ...

**Comment by vspinu** [comment]
Should be fixed.

**Comment by vspinu** [comment]
Orh... our travis scripts are not pulling julia. MELPA should be fine. Will fix tomorrow.

**Comment by jabranham** [comment]
@vspinu If people install from git, then they can read the installation instructions and see that julia-mode is a dependency. I don't understand why ESS downloads julia-mode rather than just listing it as a dependency and leaving installing dependencies up to whatever package management system people are using.

I end up with two `julia-mode.el`s on my computer. One that I have with my package manager, and then another that ESS insists on downloading when you run `make` from inside ess/lisp.

**Comment by vspinu** [comment]
Because people often want that if they do `make install`. I don't think having two julias is such a big issues. It doesn't change frequently and most the versions will match. 

We also need julia-mode.el in order to be able to compile ess-julia.el. Of course we can fetch compile and remove or do other hacks but that's too much trouble for little benefit and most importantly there will always be people wanting julia-mode as part of ess ond other people (like yourself) wanting julia-mode as stand alone. We need to go one way or another and I am quite indifferent which way we go. 

We could in principle skip compilation of ess-mode.el if julia-mode is not present and enforce for those people who want ess-julia to run an extra  `make julia-mode.el` before `make all`.

**Comment by mmaechler** [comment]
Not  sure if it belongs here:  Recently, I've got sent a file by Doug Bates with extension `.jmd`  which was obviously in  "julia markdown".   Currently my ESS switches to `ess-jags-mode`  which is obviously wrong.   Are there any Jags users reading this?  Yes, I'd vote for a `julia-markdown-mode`

**Comment by jabranham** [comment]
I occasionally use jags mode, though really only for the font locking. I'm not sure I've ever opened a jmd file.

Currently jags adds this to auto-mode-alist:

```
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.[Jj][Aa][Gg]\\'" . ess-jags-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.[Jj][Oo][Gg]\\'" . ess-jags-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.[Jj][Mm][Dd]\\'" . ess-jags-mode))
```

Since JAGS's popularity is declining we could probably prune that to just the first one.

**Comment by steve-the-bayesian** [comment]
I hit this bug (I think) today.  Tried to install ess from the emacs package installer (using the melpa archive).  

ess is an available package.                                                                                                                                                            
                                                                                                                                                                                        
     Status: Available from melpa-stable -- [Install]                                                                                                                                   
    Archive: melpa-stable                                                                                                                                                               
    Version: 18.10.2                                                                                                                                                                    
   Requires: julia-mode-0.3                                                                                                                                                             
    Summary: Emacs Speaks Statistics                                                                                                                                                    
                                                                                                                                                                                        
Emacs Speaks Statistics (ESS) is a package designed to support editing of                                                                                                               
scripts and interaction with various statistical analysis programs such as R,                                                                                                           
S-Plus, SAS, Stata and OpenBUGS/JAGS. For more details please visit ESS home                                                                                                            
page at https://ess.r-project.org/     


When I visit 'julia-mode-0.3' I get:

julia-mode is an orphan package.
     Status: Orphan.
    Archive: n/a
    Summary:

**Comment by jabranham** [comment]
@steve-the-bayesian - julia-mode removed their tags from the git history. You'll need to grab it from MELPA, not MELPA-stable

**Comment by steve-the-bayesian** [comment]
Thanks.  That did the trick.
