### ISSUE TITLE
Further output issues

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#648]
When inside a package, evaluating a line inserts a newline before the prompt:

```
>         <- empty line
> "foo"
[1] "foo"
```

Disabling namespace evaluation fixes it.

Might be related to presend filters? I get one more newline within example fields but it goes away with this patch that trims the whitespace in addition to the roxy prefix:

```diff
modified   lisp/ess-roxy.el
@@ -799,7 +799,7 @@ placed in `ess-presend-filter-functions'."
            (with-temp-buffer
              (insert string)
              (ess-roxy-entry-p)))
-      (replace-regexp-in-string ess-roxy-re "" string)
+      (replace-regexp-in-string (concat ess-roxy-re "[ \t]*") "" string)
     string))
 (add-hook 'ess-presend-filter-functions 'ess-roxy-remove-roxy-re nil)
```

**Comment by lionel-** [comment]
I also get suboptimal output when evaluating this by paragraph with nowait:

```r
1
2
3  `M-x ess-eval-paragrah`
> 1
+ 2
+ 3
[1] 1
> [1] 2
> [1] 3
```

A prompt is added to the last two lines.

Despite these little issues, the output is generally much better now and I get much less alignment issues. So thanks again!

**Comment by mmaechler** [comment]
Thanks a lot for detecting these and fixing them before 18.09!

@vspinu 's observation: Note that `R` in this case is the `roxygen` package.

**Comment by vspinu** [comment]
> A prompt is added to the last two lines.

This is another instance of the case when we cannot disambiguate between `> output` and `> input` in the process filter.

This is a tradeoff of using `nowait`. So, if you don't want to see such issues then either set `ess-inject-source` to t and abandon accumulation of incomplete input, or use eval-visibly `nil`. There is no other way till we can detect incomplete expressions on ESS side.

This is how ESS always worked with nowait and will have to stay so for 18.09.

> Note that R in this case is the roxygen package.

Nope. Roxygen has nothing to do with it.  R's `source` adds new lines in the output:

```R
> cat("\"foo\"", file = "tmp.R")
> source("tmp.R")
> source("tmp.R", echo = T)

> "foo"
[1] "foo"
```

**Comment by lionel-** [comment]
No worries. Perhaps we should collect all these known output issues in a special section in the unit tests, so we can monitor those.

**Comment by mmaechler** [comment]
Very good @vspinu.  Yes, indeed,  `source(*, echo=TRUE)` adds an empty line between each input line.
I think we (R Core) have inherited this from S / S+  ... and I never had much doubt about it (I've improved and tweaked the `source()` function quite a few times) till now, because I  always assumed this would be used interactively mainly, whereas "in code", one would not want the echo.   As this case shows, my assumption (as R programmer) was wrong.

I know think `source()` should get an optional argument allowing the caller to ask is to *not* print these extra newlines.   Of course this will not help us (ESS core) in the short term.
I still am uneasy with the fact that tracebug interferes with console output even when the user works entirely in the `*R*` buffer, by default in way that the result is different than the regular R console.

**Comment by mmaechler** [comment]
Hmmm.... I've *had* introduced such an option to the `source()` function, almost two years ago:
------------------------------------------------------------------------
r71357 | maechler | 2016-09-25 19:14:45 +0200 (Sun, 25 Sep 2016) |

new withAutoprint() based on extended source()
------------------------------------------------------------------------

So, it's   `source(*, echo=TRUE, spaced=FALSE)`  that we should use instead... at least
if(getRversion() >= "3.4")

**Comment by vspinu** [comment]
Nice!
