### ISSUE TITLE
autoload-do-load: Wrong type argument: consp, nil

### ISSUE THREAD

**Issue by LuhengStat** [emacs-ess/ESS#656]
I updated to the newest version of ESS and emacs. 
However, the R command could not be evulated with error code
" autoload-do-load: Wrong type argument: consp, nil"

**Comment by jabranham** [comment]
> I updated to the newest version of ESS and emacs.

How? What OS and how did you get the latest version of Emacs and ESS?

Can you include the full backtrace?

**Comment by LuhengStat** [comment]
The OS is macos. And I download the latest Emacs Modified for macOS.

**Comment by jabranham** [comment]
Can you post the backtrace of the error?

If you uninstall and then reinstall ESS, does that fix it?

**Comment by LuhengStat** [comment]
Sorry, I have reinstalled the emacs and ess. The error still exists when I type R:

Wrong type argument: consp, nil

**Comment by lionel-** [comment]
Can you `M-x toggle-debug-on-error`, trigger the error, and give us the backtrace of the error please.

**Comment by LuhengStat** [comment]
I have deleted all the packages files and comment all the settings of emacs. And the R runs OK.
I find maybe its because the newest version of ess-view is not compatible with ESS.

**Comment by Trends-Global** [comment]
I updated to the newest version of ESS and emacs.
However, the R command 'C-c C-j', to send a line to an R process (and start an R process if not started) triggered error code: "Wrong type argument: consp, nil"

M-x toggle-debug-on-error gives this backtrace

"Debugger entered--Lisp error: (wrong-type-argument consp nil)
  byte-code("\301\302\010\"\303\241\210\301\304\010\"\305\241\210\306\307\300\"\207" [ess-r-customize-alist assoc ess-font-lock-keywords 'ess-R-font-lock-keywords inferior-ess-font-lock-keywords 'inferior-ess-R-font-lock-keywords defalias R-customize-alist] 3)
  R()
  ess-start-process-specific("S" "R")
  ess-request-a-process("Process to use: " no-switch nil)
  ess-force-buffer-current("Process to use: ")
  ess-eval-region(56 69 nil "Eval line")
  ess-eval-line(nil)
  funcall-interactively(ess-eval-line nil)
  #<subr call-interactively>(ess-eval-line nil nil)
  apply(#<subr call-interactively> ess-eval-line (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> ess-eval-line nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (ess-eval-line nil nil))
  #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command)(ess-eval-line nil nil)
  ad-Advice-call-interactively(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) ess-eval-line nil nil)
  apply(ad-Advice-call-interactively #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) (ess-eval-line nil nil))
  call-interactively(ess-eval-line nil nil)
  command-execute(ess-eval-line)"

Anyone see the issue here?

**Comment by jabranham** [comment]
> I updated to the newest version of ESS and emacs.

Please include information on how you did so: what distro you use, whether you install ESS yourself, use your distro's package, or get it from MELPA (stable?), and any other relevant information.

This sounds like the sort of problem that might be fixed by uninstalling ESS, restarting Emacs, and re-installing ESS.

**Comment by Trends-Global** [comment]
It's been awhile since I used R on this computer (Windows 10, Emacs branches off the C drive). List-packages marked a lot of updates and I went with it ( I usually avoid that because I hate updating snippet paths for autocompletes in the init). ESS updated to the 2018 version and above errors occurred. Changed the emacs directory and reinstalled emacs using Vincent Goulet's make: GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30. Swapped over the init. 

My init checks for missing packages from listed packages and does package-refresh and installs. It ran into some problem with 'Golden Ratio' and wouldn't install the rest. Copied and pasted all the packages from the renamed directory to get it working. 

Couple tests to fix the ess send line: deleted related ess packages 1 by 1, restarted and tested R. Packages: ess-R-data-view, ess-R-object-popup, ess-smart-equals, ess-smart-underscore. Same error all the way through. 

Toggled off ess-use-flymake (a flymake error came up before the wrong type argument error). I didn't have flymake installed, but when I installed it, the flymake error still came up. Toggling off ess-use-flymake fixed the flymake error, only the wrong type error remained. 

Lastly, deleted ess2018 and pasted in ess-20170327.248. This fixed the error so can send a line of code (and start an ess process) from a buffer with a .R in it. Now the wrong type argument bug comes up when I install the ess accessory packages listed above from melpa. They do not install.

Another thing: packages gives ess dependency status, implying ess is a dependency of another package I have installed and cannot be uninstalled and reinstalled through packages (only by deleting the directory, or other methods). 

Maybe some mandatory calls from ess2018 to functions that no longer exist or need to exist?

**Comment by jabranham** [comment]
> Another thing: packages gives ess dependency status, implying ess is a dependency of another package I have installed and cannot be uninstalled and reinstalled through packages (only by deleting the directory, or other methods).

Do you still get this error if you remove the packages that depend on ESS? Some of them are quite old and aren't maintained anymore.
