### ISSUE TITLE
ess smart assing key no longer works

### ISSUE THREAD

**Issue by arturakb** [emacs-ess/ESS#659]
I have this in my .emacs file. It used to work fine but no longer works. Pressing ";" just inserts ";".

(require 'ess-site)
(require 'ess-rutils)
....
;; smart assign
(setq ess-smart-S-assign-key ";")  ;if ";" needed, press ";" key twice
(ess-toggle-S-assign nil)
(ess-toggle-underscore nil) ;leave underscore key alone!

Thanks.

**Comment by vspinu** [comment]
I think all you need to do now is to leave the first line. But it must be set before ESS has been loaded. 

@jabranham In principle we could check for `ess-smart-S-assign` key every time ess-mode is loaded and assign it in the local map instead of doing it on ess startup. This way users could re-assign it in the middle of the session.

**Comment by lionel-** [comment]
Good idea, let's do that. Issues of configuration timing can be so confusing.

**Comment by arturakb** [comment]
OK, that worked. I've kept only the following line and put it before the require statements.
(setq ess-smart-S-assign-key ";") ;if ";" needed, press ";" key twice

Thanks.
