### ISSUE TITLE
ess-switch-to-inferior-or-script-buffer activates frame on other desktop

### ISSUE THREAD

**Issue by torbjorn** [emacs-ess/ESS#687]
I use emacs on a linux pc with multiple desktop (most linux desktops have this)

Using emacs server, if I have an emacs frame with an *R* buffer on another desktop, and this happens to be used by an R script buffer that Im working with on my current desktop, then switch, all that happens is that it defocuses my current emacs window and probably focuses that on the other desktop. But I have to go there myself to see it. Which is not at all what I want.

I would want to see that frame in my current window, I don't mind that its viewed in multiple frames on multiple desktops.

Also I use ido which is probably related.

**Comment by vspinu** [comment]
I am just wondering, wouldn't it make more sense to have two separate instances of emacs running on different desktops? There are so many posibilites out there that whatever we do there will be rare use cases like yours which won't fit the pattern. 

Not tested but if overwriting `ess-buffer-visible-other-frame` to always return nil should "fix" your problem:

```el
(defun ess-buffer-visible-other-frame (_) nil)
```

I don't think we could (or should) implement something specific for this use case. We are already doing one tiny bit too much in that switcher for historical reasons.

**Comment by jabranham** [comment]
This has also annoyed me from time to time but I'm not sure there's much we can do about it. I think in general Emacs can't detect changes to frames' visibility that the window manager makes.

Since I always want to use an inferior process in the same frame as the script though, perhaps it would make sense to add a boolean defcustom that controls whether or not ESS looks at other frames? If that's OK with you @vspinu I'll write it up and submit it. I'll keep the current behavior as default of course.

**Comment by vspinu** [comment]
Sure. I don't know if we already have any configuration of this behavior, but if we do maybe we could extend it without introducing new customs. There is also similar machinery for help buffers. Would be good if the logic were similar in the two sub-systems.

**Comment by jabranham** [comment]
I believe this should be fixed in `next` so closing this issue.
