### ISSUE TITLE
openblas threading problem when running R through ess

### ISSUE THREAD

**Issue by kalle0** [emacs-ess/ESS#718]
Hi,
I am using ess for R. I recently noticed that matrix multiplication via openblas have gone single threading, with hyper-threading switch on to two threads maximum. This does not happen when R is run in bash or via Rscript. So I imagine that the bug must be somewhere in ess. I reinstalled ess (from Arch repository) but had no luck. I am running linux, Arch, kernel version 4.18.12. Any ideas??

Thanks a lot.
Cheers.

**Comment by mmaechler** [comment]
Well, this sounds *VERY* improbable and i strongly  hope your diagnosis to be wrong...

Did you use  sessionInfo()  in all instances and carefully compare what you see?
You can / maybe must   also use  `R.home()` to see where your R was taken from (in case you also have several R versions installed as I do.

**Comment by kalle0** [comment]
Hi Martin, thanks for the quick response. Unfortunately I cannot give you any relief. What I did was:

a <- sessionInfo()
a <- c(a,R.home())
a <- c(a,Sys.getenv("MC_CORES"))
save(a,file="sessioninfo")

I run this script in ess and Rscript. In between I copied the output to "sessioninfo.ess" or "sessioninfo.rscript". Then I run this script which simply compares the list elements (I skipped item 6 because of being class "packageDescription"):

load("sessioninfo.ess")
b <- a
load("sessioninfo.rscript")
for(i in 1:length(a)){
    if(i==6) next
    if(class(a[[i]])=="list"){
        x <- a[[i]]
        y <- b[[i]]
        for(j in 1:length(x)){
            if(class(x[[j]])=="list"){
                stop("problem1")
            }else if(class(x[[j]])=="character"){
                for(k in 1:length(x[[j]])){
                    if(x[[j]][k]!=y[[j]][k]){
                        stop("xxx1")
                    }
                }
            }else{
                cat(class(x[[j]]),"\n")
                stop("problem2")
            }
        }
    }else if(class(a[[i]])=="character"){
        for(j in 1:length(a[[i]]))
            if(a[[i]][j]!=b[[i]][j]){
                stop("xxx1")
            }
    }else{
        stop("problem3")
    }
}

This script did not yield any differences.

"detectCores" from package "parallel" showed the right number of cores in both, ess and Rscript.

Running this code:

x <- matrix(1,10000,10000)
y <- matrix(1,10000,10000)
system.time(z <- x%*%y)

yielded

   user  system elapsed 
 82.534   0.361  41.901 
for the ess version, and

user  system elapsed 
114.153   0.350  15.041
for the Rscript version.
With regard to threading, I think both system should use the same environment variables. At least I have no special threading provision for ess and Rscript in my bashrc and .emacs. My .emacs has only
(setq load-path (cons "/usr/share/emacs/site-lisp/ess" load-path))
(require 'ess-site)
(setq  ess-ask-for-ess-directory nil)

Cheers

Karl

**Comment by kalle0** [comment]
Update: I downloaded the ess source and compiled from scratch, but found no changes.

Cheers

**Comment by jabranham** [comment]
I haven't had coffee yet so maybe I'm missing something obvious but what makes you think that ESS isn't taking advantage of threading? Looks like ESS actually ran slightly faster than the Rscript version.

**Comment by kalle0** [comment]
Hi, have a look again. ess took 41.9 sec, rscript 15.04 sec.

Thanks to he unknown making my example more readable.

Cheers

**Comment by jabranham** [comment]
Ah, indeed. The perils of commenting before coffee. You can make github render code prettier by surrounding it in three backticks: https://guides.github.com/features/mastering-markdown/

I get similar results when running 

```R
x <- matrix(1,10000,10000)
y <- matrix(1,10000,10000)
system.time(z <- x%*%y)
```

inside of ESS+Emacs, just inside Emacs, and outside of Emacs. I'm not quite sure how you'd get different results without setting some of those environmental variables already mentioned. Maybe some weird compile-time Emacs option?

Can you confirm that you see this outside of ESS but inside of Emacs please:

```
M-x shell 
R
x <- matrix(1,10000,10000)
y <- matrix(1,10000,10000)
system.time(z <- x%*%y)
```

**Comment by mmaechler** [comment]
Your timings *both* have `user` considerably larger than `elapsed`  so  *both* cases do parallelize.
It looks like Emacs (probably rather than ESS) is only granting 2 cores to the inferior process... (whereas your Rscript was allowed to use *all* cores?)... but I'd say Emacs is right in doing what it does:  If you use an interactive program (and you are using many, apart from Emacs also the windowing system), it is "stupid" to allow other processes to take all your cores and I assume Emacs uses something like `ulimit` (shell command, look it up!) or something similar to limit the number of threads.

**Comment by kalle0** [comment]
@mmaechler 
I am not aware that ulimit has capacities to limit the threading. Also, as I have used ess for a long time emacs "non-stupidity" must have developed quite recently. The parallelization via ess appears to be core bound. With 4 cores and 8 threads this means that if my bios would allow me to switch off hyperthreading there would be no parallelization at all when running ess.

@jabranham 
Spot on. Running the script via Rscript inside emacs shell yields 200% cpu load (hyperthreading switched on). Rscript via bash yields 800%. So I assume that the problem is inside emacs and not ess. Unfortunately a quick google did not really yield something useful. So any hint how to get ess back on track is highly appreciated.

**Comment by jabranham** [comment]
@kalle0 You're using `openblas` from `[community]` and not `blas` from `[extra]`, right? `pacman -S r` will get `blas` by default, which is quite a bit slower than `openblas`. You can safely switch with `pacman -Syu openblas`. 

Other than that I'm not quite sure what's the problem. I just double-checked this on an arch install and it works just fine for me, though I compile my own emacs rather than use the one they compile.

I'm going to close this since it's not an ESS issue. It's either an Arch issue, an Emacs issue, or an issue on your machine (though unlikely given what you've told us previously) but I'm not sure which.

That said, feel free to keep asking questions here and I'll help if I can.

**Comment by vspinu** [comment]
Sounds like an env variables issue. If you run emacs from shell then R in ess it might get you your 800%.
