### ISSUE TITLE
info location in elpa

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#72]
Now ESS puts all info files in the main directory of the elpa ESS folder. Could it be possible to put all info files in the "info" sub folder, so that it looks cleaner?

**Comment by jabranham** [comment]
@vspinu if you're going to send a PR to the MELPA folks regarding #543, we might as well tackle this issue at the same time since implementing this would require another PR.

That said, I don't think we need to move the info files. Other packages (e.g. magit, use-package) also put their info files at the top level, and the Elisp manual seems to suggest that this is considered best practice:

>  If the content directory contains a file named ‘dir’, this is assumed
> to be an Info directory file made with ‘install-info’.  *Note Invoking
> install-info: (texinfo)Invoking install-info.  The relevant Info files
> should also be present in the content directory.  In this case, Emacs
> will automatically add the content directory to ‘Info-directory-list’
> when the package is activated.

and `content-directory  just means 

> The tar file must be named ‘NAME-VERSION.tar’,
> where NAME is the package name and VERSION is the version number.  Its
> contents, once extracted, must all appear in a directory named
> ‘NAME-VERSION’, the “content directory”.

So my vote is to close this issue.

**Comment by vspinu** [comment]
@jabranham, great research! Indeed, looks like what we do is indeed the standard.
