### ISSUE TITLE
ess-eval-region-or-line-and-step bug in Melpa release ess-20181019.1636

### ISSUE THREAD

**Issue by kuwze** [emacs-ess/ESS#725]
ess-20181019.1636 introduced a bug that prevents an ESS R buffer from properly running ess-eval-region-or-line-and-step (via C-return). ess-20181010.1844 does not have this bug.

Instead of just complaining, I thought I might as well ask: what can I do to help?

**Comment by vspinu** [comment]
How exactly does it "prevent" running. Code example, error? Works fine for me.

**Comment by kuwze** [comment]
I am very new to R, and I know how unlikely it is for a novice to stumble on a bug that isn't their own, but I thought this was a real bug because it goes away if I change the version of the library.

The issue shows itself when stepping through this code for example:

``` R

library("ggplot2")
ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species)) +
  geom_point()

```
Here is the transcript of hitting C-return over it:

> > > library("ggplot2")
> > Error in ss(file, echo = visibly, local = local, print.eval = output,  : 
>   /tmp/test.org[*Org Src test.org[ R ]*]!byNGlJ:2:0: unexpected end of input
> 1: ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species)) +
>    ^
> > > geom_point()
> geom_point: na.rm = FALSE
> stat_identity: na.rm = FALSE
> position_identity 
> > 

On other random R projects when I hit C-enter it repeats that error of "unexpected end of input". This only happens in ess-20181019.1636, not ess-20181010.1844.

**Comment by mmaechler** [comment]
I'm not sure this is related.  
In my personal (actually our "group wise") settings, I've set  `ess-eval-visibly-p` to `nil` for many years, possibly even since last millennium..
The change now has changed my most used key sequence in ESS,  `C-c C-n` indeed bound to  `ess-eval-region-or-line-and-step`  to evaluate invisibly.... even though it has been documented (still is) to evaluate  *visibly* ... and yes, this always was not influenced by the  `ess-eval-visibly-p` setting at all..
Unfortunately this misfeature has crept into the released `18.10` ... that's very very unfortunate.

**Comment by mmaechler** [comment]
The previous --- > 20 years ---  setting had been very much on purpose used different behavior for
`ess-eval-line`  and `ess-eval-*-and-step`   We old time users did exactly want both possibilities:
"visibly" and "invisibly" depending on the key stroke (`C-c C-j` and `C-c C-n` respectively).

We can discuss abandoning that difference in `next`, but really not for `18.10` with a last minute change.. (that I had unfortunately not tried before releasing).

**Comment by kuwze** [comment]
So this has gotten way beyond my understanding. What do you recommend a neophyte like me do to adapt to this change?

**Comment by jabranham** [comment]
You can disable the project namespace evaluation with `M-x ess-r-package-mode`.

**Comment by vspinu** [comment]
This one has to do with the namespaced evaluation which is currently not toggled by package mode. Use C-c C-t C-s to disable the namespaced evaluation. Or set `ess-r-evaluation-env` to nil in ess-mode-hook. 

I have just commited a fix for the visual part. Both `C-c C-n` and `C-RET` are now evaluating lines visually.

**Comment by mmaechler** [comment]
This (`C-c C-n`) is still not perfect (and differing from 17.10 behavior):
It now does show the *R* buffer if no R buffer was visible, but it needs to be smarter:

Of course I often run `*R*` and `*R-devel*` (different versions of R) in different ESS buffers. And from the *same*  `foo.R` (R script file buffer) I want to send code  first to `*R*` and then to `*R-devel*`.
For that, I use `C-c C-z` to switch the R process (e.g., from `*R*` to`*R-devel*`) that switch works, but *then*, sending that line still shows the "old" `*R*` buffer which is no longer current/ no longer the R process "linked" to my `foo.R`.  In that case, I expect that instead of `*R*`, the `*R-devel*` becomes my 2nd visible buffer. ...  which was nicely working previously

**Comment by vspinu** [comment]
I don't see what you describe. Association mechanism in those functions is just as in any other eval function. 

You cannot use `C-c C-z` to switch processes. It's `C-c C-s`. Once process is switched the code is sent to the right place.

**Comment by mmaechler** [comment]
> You cannot use C-c C-z to switch processes. It's C-c C-s. Once process is switched the code is sent to the right place.

Yes, of course it `C-c C-s` that was typo..   and ... interestingly or not, at least today the code is sent to the right place... may I had not worked with the very latest version of the `master` branch when I wrote the above.

There is another glitch though:   In `Rd-mode`  (for the examples),  `C-c C-n` is still bound to the wrong not-always-visible `ess-eval-*` incantation..  ... ditto for  `ess-help-mode`.   We should ensure this uses the same keybinding in all our modes.

**Comment by vspinu** [comment]
Arh. Indeed. Fixed in master.

**Comment by jabranham** [comment]
This is fixed, right? Closing.
