### ISSUE TITLE
Julia functions are not recognized by ess-function-pattern

### ISSUE THREAD

**Issue by pmcvay** [emacs-ess/ESS#777]
Julia functions are not recognized when running `ess-eval-function` with the cursor inside the function

```julia
function test(a::Int64)
    @show a
end
```
results in 
```
Point is not in a function according to `ess-function-pattern`

**Comment by nverno** [comment]
One option is using `ess-eval-region-or-function-or-paragraph`

**Comment by jabranham** [comment]
In #785 we've reworked `ess-eval-function` to rely on `beginning-of-defun` and `end-of-defun`, which are generic Emacs commands rather than ess-specific. You should ask the julia-mode devs to add functions to `beginning-of-defun-function` and `end-of-defun-function` that enable navigation within functions.
