### ISSUE TITLE
Allow control over indentation of closing parenthesis in argument list of function call

### ISSUE THREAD

**Issue by kevinushey** [emacs-ess/ESS#88]
Allow the user to control the indentation level for the closing parenthesis of an argument list, e.g. allowing

```
function_call(
  a,
  b,
  c
)
```

vs. the default

```
function_call(
  a,
  b,
  c
  )
```

Emacs gives control over this in C mode through `arglist-close`, as described in `C-h v c-offsets-alist`, so perhaps the code there can be leveraged.

(Additionally, as Vitalie pointed out in the mailing list, this style of indentation is preferred only if no argument is present on the same line as the function call, e.g. vertical alignment is likely preferable for

```
function_call(a,
              b,
              c
              )
```

**Comment by archenemies** [comment]
Thank you all for fixing this. I was going to report a similar issue but it turned out that I was using an old version of ESS. Now the indentation is just how I like it - better than the default settings for emacs-lisp or C. And the documentation for `ess-style-alist` and related variables is very good. I'm impressed with your hard work and with the excellent results you've achieved.

**Comment by vspinu** [comment]
Those changes were not due to this fix. @lionel- reworte the indentation engine in the mid 2015. All credit goes to him.

**Comment by archenemies** [comment]
Well, thanks to all of you.
