### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#910]
Are we interested in adding python support to ESS? I've hacked together a working file. It's quite small and simple at the moment, but seems to work well for a lot of things (REPL interaction, help display, etc). If people are interested I can clean it up a bit and submit the code.

The general idea of the implementation as it stands is to take advantage of ESS's keymaps and REPL interaction. I don't have plans to add stuff like completion support and eldoc support since there's good implementations for that stuff already in eglot, lsp-mode, anaconda, etc.

**Comment by lionel-** [comment]
Sounds great! REPL + help would be huge already.

Agreed that completion stuff is outside of scope for ESS and belongs to the language modes.

**Comment by vspinu** [comment]
There is a decent support a la ESS in [python-x](https://gitlab.com/wavexx/python-x.el) and @wavexx has some very good ideas about the interaction which we miss at ESS. See this [issue](https://github.com/wavexx/python-x.el/issues/8). 

I like the idea and I think it's worth it. The only thing is that I would like to make it right from the start, and that means doing session/project management right. This basically means making ESS work with sesman. I have been swamped with some personal stuff atm unfortunately. No need to wait for me though. I will hack into what you have put together. Let's just not advertise it as yet.

**Comment by wavexx** [comment]
I didn't follow through lately, but... do we have python support now in ESS? =)

**Comment by jabranham** [comment]
@wavexx No. Most of the python machines I work with don't have R and it's not possible to develop on ESS without R (#925), so I can't really implement this in ESS. I haven't decided yet if I'll maintain it as a third-party package or if I'll concentrate on improving python's interaction with the REPL upstream.

If you want, you can check out the python branch of my ESS git repo. It should work OKish.

**Comment by vspinu** [comment]
> Most of the python machines I work with don't have R and it's not possible to develop on ESS without R (#925), so I can't really implement this in ESS.

Sorry, but this is a ridiculous reason. You cannot install software on your development computers? Extremely hard to believe that. You develop ESS on company servers, or what?

**Comment by lionel-** [comment]
This harsh reply is uncalled for. Besides, company desktops and laptops are often locked up as well.

**Comment by vspinu** [comment]
What is uncalled for is closing this very important initiative due to a personal frustration with #925. @jabranham added tons of R related stuff to ESS, to bring now an excuse that he doesn't have R on his machines. We all know that without @jabranham we are very unlikely to pull this through. So yeh, I am openly frustrated.

**Comment by jjzmajic** [comment]
I don't want to jump into the argument, I'm just here to check up on something that is evidently a pain point in the Emacs community:

- https://www.reddit.com/r/emacs/comments/6ax3xv/elpy_for_python_data_scienceanalysis/ (note the overwhelming number of personal hacks)
- https://stackoverflow.com/questions/10762171/is-there-a-good-emacs-plugin-for-python-just-like-ess-for-r-and-slime-for-lisp
- http://www.jesshamrick.com/2012/09/18/emacs-as-a-python-ide/ (outdated)
- https://stat.ethz.ch/pipermail/ess-help/2015-July/010628.html
- there's obviously more, but you get my point

@wavexx did some great work with python-x, but it is obviously a collection of one man's personal preferences. A great one, but very workflow specific (see [this discussion](https://gitlab.com/wavexx/python-x.el/issues/5) to see what I'm talking about).

Regardless of whether ESS gets split up, turned into a minor-mode, or stays as is, I think python should be a "part" of it. However you slice it, ESS is where it's at when it comes to data science and  Emacs. If it's not done here, it won't be done anywhere.

I understand that this is a volunteer effort, and development takes time and energy. But can this issue at least be opened again? Because this makes it seem like python-related contributions are not only low-priority (which they really shouldn't be) but also discouraged.

**Comment by wavexx** [comment]
> @wavexx did some great work with python-x, but it is obviously a collection of one man's personal preferences. A great one, but very workflow specific (see [this discussion](https://gitlab.com/wavexx/python-x.el/issues/5) to see what I'm talking about).

More than a persornal choice, it's first a time constraint. python-x is a thin layer on top of python mode, there's a ton of stuff that cannot be done properly, so a result I changed a bit the way things work.

That being said, I keep alternating between ESS (R), python-x, elpy and ein. I'm glad ein exists, but while I think notebook interfaces are great for teaching (and I do teach python too), I came to dislike it with a passion for anything *but* teaching. I also really, really dislike the amount of infrastructure required just to run a notebook.

While I'm not perfectly happy with python-x (mostly to the way the buffers/processes are bound) I also feel the ESS approach to evaluation a bit odd/limiting after you're used to cells/blocks.

I wish I had something else...

**Comment by jjzmajic** [comment]
For anyone looking for a solution in the meantime, I get around the the frustrations I share with @wavexx (buffer-process association, and deep discomfort with notebooks) using [emacs-jupyter](https://github.com/dzop/emacs-jupyter).

I would prefer something closer to the metal, but it's all I have for now. If anyone is interested, here's my config (note that there are some heavy personal abstractions and loose couplings in there): https://gitlab.com/jjzmajic/ansible-dots/-/blob/master/emacs/macs+/python+.el

PS: @wavexx, thank you for saving my butt with python-x in 2 classes and an internship. It has served me well while I used it.

**Comment by vspinu** [comment]
I will get down to this at some point. It's a number 2 priority for me personally after streamlining session management with sesman. Sesman is a prerequisite for python as I would like to make the session association business right from the very start. 

Unfortunately I have just switched jobs and it will take a few more months before I can even start working on this.

**Comment by cimentadaj** [comment]
+1 This would be a game changer.

**Comment by cimentadaj** [comment]
@vspinu if any help is needed, I'd be happy to chime in. I'm really an elisp beginner but if there's room for beginner contributions, I'd be happy to put some time into it.

**Comment by henningninneh** [comment]
OMG, some modicum in python support within ESS would be fantastic, especially now with Quarto. In RStudio, evaluating a mix of R and python code chunks is a non-issue. It would be great if I could just C-c C-c on python code blocks like I can on R code blocks. There are polymode hacks that allow python code block evaluation in Rmd/qmd files, but not as elegant as with ESS' `ess-eval-region-or-function-or-paragraph-and-step`. For example
Here's another example of a personal hack https://emacs.stackexchange.com/questions/74478/evaluate-single-python-code-blocks-in-a-quarto-file-like-in-r-studio-or-jupyter/74579?noredirect=1#74579
